### ISSUE TITLE
Laravel Sanctum Token After Authorization

### ISSUE THREAD

**Issue by rendybustari** [laravel/sanctum#112]
I am using Laravel Sanctum in my project. for request login, I using Auth::loginUsingId($user->id, true) and create token with sanctum,

when i to try request data user with false Bearer token (and empty bearer token), I still get the data, event I delete field in table personal_access_token, so how I can check if the bearer token is same with token in personal_access_tokens?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
