### ISSUE TITLE
canToken retuns null/empty string in FormRequest

### ISSUE THREAD

**Issue by joveice** [laravel/sanctum#115]
- Sanctum Version: 2.1.0
- Laravel Version: 7.3.0
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:
The function `canToken` returns null or a empty string when used in a `FormRequest

### Steps To Reproduce:
1. Create a token with a ability, let's say `user:create`
2. Create a `FormRequest`
3. Add this to the authorize function `return $this->user()->tokenCan('user:create');`
4. Add a route to a controller which uses the `FormRequest` you created
5. Attempt to use it, it gives `This action is unauthorized`. Log it to the log file and it shows as empty

Not sure if this is a bug / missing feature or if I'm attempting to do something it wasn't designed to do.

**Comment by clugg** [comment]
The code logically indicates that `tokenCan` can only return a boolean - can you share the reproduction steps you used to prove that it returns null or an empty string? If you remove the form request from the equation and run the exact same route directly to a controller, does tokenCan work inside the controller?

If it doesn't work inside the controller, I am guessing you are missing the `auth:sanctum` middleware from your route.

**Comment by joveice** [comment]
**StoreGatewayRequest**
```
<?php

namespace App\Http\Requests\Api\Services\Victoria;

use Illuminate\Foundation\Http\FormRequest;

class StoreGatewayRequest extends FormRequest
{
    public function rules()
    {
        return [
            'name' => ['unique:service_victoria_gateways'],
            'password' => ['sometimes', 'nullable']
        ];
    }

    public function authorize()
    {
        return $this->user()->tokenCan('victora:all');
    }
}
```
Add a `Log::debug('test', [$this->user()->tokenCan('victora:all')]);` and it returns `false`so I have done something wrong in the initial test. but this is still wrong?
add this logging in the controller `Log::debug('test', [$user->tokenCan('victoria:all')]);` and it returns `true` if you return true in the form to not use that validation
**Route**
```
Route::group(['prefix' => 'v1'], function () {
    Route::group(['prefix' => 'services'], function () {
        Route::group(['prefix' => 'victoria'], function () {
            Route::post('authenticate', 'Api\V1\Services\VictoriaController@authenticate');
            Route::group(['prefix' => 'gateway', 'middleware' => 'auth:sanctum'], function ()
            {
                Route::post('create', 'Api\V1\Services\VictoriaController@createGateway');
...
```

So correction, it seems to return false when it should have returned true.

**Comment by nanaaikinson24** [comment]
Can laravel/sanctum be used without auth scaffolding?

**Comment by driesvints** [comment]
@nanaaikinson24 no

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by joveice** [comment]
> Hey there,
> 
> Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.
> 
>     * [Laracasts Forums](https://laracasts.com/discuss)
> 
>     * [Laravel.io Forums](https://laravel.io/forum)
> 
>     * [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
> 
>     * [Discord](https://discordapp.com/invite/KxwQuKb)
> 
>     * [Larachat](https://larachat.co)
> 
>     * [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
> 
> 
> Thanks!

Did you mean to close this? Isn't this a bug?

**Comment by joveice** [comment]
Bah, it works! it was a simple spelling mistake :(

**Comment by aiman1717a** [comment]
I am actually having the same issue you had. how did you solve the issue?

**Comment by joveice** [comment]
> I am actually having the same issue you had. how did you solve the issue?
> 
> In my case im just authenticating view an api route and check the tokenCan() method but it returns empy

I had a typo.

**Comment by aiman1717a** [comment]
i checked again and i don't have a type in token abilities or in anything else
