### ISSUE TITLE
Auto Login in Multiple SPA

### ISSUE THREAD

**Issue by rohan-khatri** [laravel/sanctum#121]
- Sanctum Version: 2.1
- Laravel Version: 6.2
- PHP Version: 7.2
- Database Driver & Version: mysql@5.7

### Description:
i am facing automatic login issue for multiple SPA with single backend.

currently, i am using two SPA, in which same backend is used, and whenever user loggingIn in `one.domain.test` SPA, then user also get loggedIn in `second.domain.test`.

so, i want to prevent this scenario without changing my SESSION_DOMAIN, ( because my backend is gone be used for multiple SPA ).

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
