### ISSUE TITLE
EnsureFrontendRequestsAreStateful and EncryptCookies

### ISSUE THREAD

**Issue by ggolda** [laravel/sanctum#122]
- Sanctum Version: 2.0.0
- Laravel Version: 7.2.2
- PHP Version: 7.4.4
- Database Driver & Version:

### Description:
I'm not sure that this problem can be classified as a bug, but I had to dig into laravel sources to find a solution to it.

Problem: `EncryptCookies` middleware in `EnsureFrontendRequestsAreStateful` is not getting applied when request comes not from a frontend. I understand that it is how it was intended to work, but some libraries including `laravel-echo-server` are unable to work with sanctum protected routes until a hack workaround is applied.

### Steps To Reproduce:

Tools that are working by reusing laravel's session are not working with sanctum because they are not passing a `Referer` http header. Without this header, `EncryptCookies` middleware is not applied and `SessionGuard` is unable to find a user.

It can be fixed in third-party libraries by adding a referer header, but it will require to update all libraries that are working by reusing laravel session cookie. As I understand, the goal of Sanctum was a drop-in replacement for default `web/api` authentication so probably it can be an issue.

P.S. if its not a bug, I suggest to update documentation for Sanctum and include this hack in `Laravel Echo` section:

```js
window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname,
    auth: {
      headers: {
        'Referer': window.location.hostname
      }
    }
});
```

**Comment by driesvints** [comment]
Referer header is indeed needed here.
