### ISSUE TITLE
I wonder if I can use sanctum on diffrent domain.

### ISSUE THREAD

**Issue by irsyadadl** [laravel/sanctum#126]
spa: abc.com,
api: xyz.com.

Do you know how to connect this two diffrent domain ?

**Comment by driesvints** [comment]
Please see https://laravel.com/docs/7.x/sanctum

<img width="711" alt="Screenshot 2020-04-14 at 11 24 01" src="https://user-images.githubusercontent.com/594614/79208538-75f2a900-7e42-11ea-9c93-2cbb8fe2fa11.png">
