### ISSUE TITLE
TDD with Sanctum: Issue with user logout case  

### ISSUE THREAD

**Issue by arifkhn46** [laravel/sanctum#127]
- Sanctum Version: #.#.#
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
My issue is related to TDD with Sanctum. I am writing a use case to logout a user, so on Logout request, I delete all the user tokens so that every token issued previously becomes invalid for further requests. 

Following is the feature test case:

```
    /** @test */
    public function a_user_can_logout()
    {

        // $this->withoutExceptionHandling();
        $this->jsonPost(route('api.user.logout'))->assertStatus(401);

        $user = factory('App\User')->create();

        $response = $this->json('POST', route('api.user.login'), [
            'email'=> $user->email,
            'password' => 'password'
        ])->assertStatus(200);
        
        $this->jsonPost(route('api.user.logout'), [], $response->json()['access_token'])->assertStatus(200);
                
        $this->jsonPost(route('api.user.profile'), [], $response->json()['access_token'])->assertStatus(401);
    }
```

Now on logout request following method runs:

```
    public function logout()
    {
        auth()->user()->tokens()->delete();
        return response()->json(['message' => 'Successfully logged out']);
    }
```

Now comes the bug part, in the last assertion i.e. `$this->jsonPost(route('api.user.profile'), [], $response->json()['access_token'])->assertStatus(401);`  I am calling user profile API which should return the status as 401 but it always returns 200. 

![Screenshot 2020-04-14 at 8 12 47 PM](https://user-images.githubusercontent.com/12694008/79237888-51bbba00-7e8c-11ea-9aae-81a1a645fab2.png)

My profit method:
  
```
public function profile()
    {
        return response()->json(auth()->user());
    }
```

I tried to debug the issue and following is my observation(s):

1. **I am facing this issue when I run this feature test through the command line. If I test the same thing on POSTMAN Client the functionality is just working fine. So this issue is related to TDD.**

2.  There is a method in the class Illuminate/Auth/RequestGuard.php

 ```
    public function user()
    {
        // If we've already retrieved the user for the current request we can just
        // return it back immediately. We do not want to fetch the user data on
        // every call to this method because that would be tremendously slow.
        if (! is_null($this->user)) {
            return $this->user;
        }

        return $this->user = call_user_func(
            $this->callback, $this->request, $this->getProvider()
        );
    }
```
In this method Laravel is caching user object for performance optimization. And If we comment out the caching code i.e. 

```
 if (! is_null($this->user)) {
      return $this->user;
 }
```
my feature test case runs perfectly.

![Screenshot 2020-04-14 at 8 10 56 PM](https://user-images.githubusercontent.com/12694008/79237688-14572c80-7e8c-11ea-9191-c14da5ab1317.png)

Following is my route list:

![Screenshot 2020-04-14 at 7 45 27 PM](https://user-images.githubusercontent.com/12694008/79234870-82015980-7e88-11ea-83b8-e4a1ce9f2a4e.png)

### Steps To Reproduce:

1. Setup Laravel 7 and Sanctum
2. Setup API routes for login, log out, and user profile or any sanctum token protected route.
3. Create a feature test or use the above feature test code.
4. Run the tests.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by driesvints** [comment]
Next time please also don't ignore the issue template.
