### ISSUE TITLE
Change default table name.

### ISSUE THREAD

**Issue by nciardo** [laravel/sanctum#130]
Hi guys.
What about the ability to change the default table name (at the moment – `personal_access_tokens`) through the config file?
It would be appreciated.
Thank you,
Niccolò.

**Comment by driesvints** [comment]
You can overwrite the model and then set it using `Sanctum::usePersonalAccessTokenModel()`

**Comment by nciardo** [comment]
@driesvints ok, thank you, it's a way!
But it would be "better" set a different table name in `config/sanctum.php`, because your solution "enforce" us to define a "new model" – not always "needed".
My 2 cents.

**Comment by simaremare** [comment]
It is in the documentation:
https://laravel.com/docs/9.x/sanctum#overriding-default-models

But I would also love to have it in the config file.
