### ISSUE TITLE
after Login with santcum go to Home

### ISSUE THREAD

**Issue by MohammadNajjary** [laravel/sanctum#133]
- Sanctum Version: 2.2
- Laravel Version: 6.2
- PHP Version: 7.3.14

### Description:
this is my vue login file:

```
<template>
  <div class="home">
    <form action="#" method="POST">
        <div><input type="email" name="email" placeholder="email"></div>
        <div><input type="password" name="password" placeholder="password"></div>
        <div><button type="submit" @click.prevent="login">login</button></div>

    </form>
  </div>
</template>

<script>

import axios from 'axios'

axios.defaults.withCredentials = true;
axios.defaults.baseURL ='http://localhost'
export default {
  name: 'Home',

  methods:{
    login(){
        axios.get('/sanctum/csrf-cookie').then(response => {
           axios.post('/login',{
            email:'admin@admin.com',
            password:'123456'
          })
          .then(response=>{
            console.log(response)
          })
        });
    }
  }

}
</script>
```
after login request with axios laravel go to home url and i have error in console
![image](https://user-images.githubusercontent.com/17889773/80700412-f24be400-8af2-11ea-8bd5-f6f979fc8129.png)

I'm sure the password and username are correct. Shouldn't html be returned to me when I use axios.
![image](https://user-images.githubusercontent.com/17889773/80700859-a483ab80-8af3-11ea-8979-564f9ef95405.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by MohammadNajjary** [comment]
please see this :
https://stackoverflow.com/questions/tagged/laravel-sanctum

Most users have the same problem and no one has given the right answer.It is a good idea to provide a solution to this problem instead of sending a duplicate message.

**Comment by harrysbaraini** [comment]
It's hard to provide a solution for your error just by looking your vue component. A lot of things may be going on, like cors, Auth middleware, content negotiation.

About redirection to /home, ensure you're sending proper Accept and ContentType headers (application/json).

About 401, I had a similar issue, but I eventually found out that I wasn't using auth guards in the right way.

**Comment by Dartui** [comment]
"Problem" is in `RedirectIfAuthenticated` middleware, which is aliased to `guest`. Base `LoginController` is protected by `guest` middleware, so if you once logged in you will hit this part of code every time you try to log in again:
```php
        if (Auth::guard($guard)->check()) {
            return redirect(RouteServiceProvider::HOME);
        }
```

**Comment by Asepdadan** [comment]
in local work, but production use shared hosting not work,  where that's wrong

**Comment by sausin** [comment]
The following updated code inside the `RedirectIfAuthenticated` controller works:

```php
if (Auth::guard($guard)->check()) {
    if ($request->wantsJson()) {
        return response()->json(['result' => 'success'], 200);
    }

    return redirect(RouteServiceProvider::HOME);
 }
```
