### ISSUE TITLE
Support For Lumen

### ISSUE THREAD

**Issue by Elshaden** [laravel/sanctum#134]
Hi
Is there anyway to install Sanctum on Laravel Lumen

**Comment by driesvints** [comment]
No, please use the Laravel framework.

**Comment by ahsyam** [comment]
Is lumen still not supported?

**Comment by gaurang-joshi** [comment]
Is sanctum still not supported for Lumen?

**Comment by Elshaden** [comment]
No,
and by the looks of it there will never be.
