### ISSUE TITLE
Issues with getting CSRF cookie from domain.test

### ISSUE THREAD

**Issue by goranculibrk** [laravel/sanctum#137]
- Sanctum Version: 2.3
- Laravel Version: 7.9.2
- PHP Version: 7.4.3
- Database Driver & Version: mysql, mariadb 10.4

### Description:
Hey guys. I'm trying to build an app that will consume Laravel APIs and I'm trying to use Sanctum for authentication. I've check a whole bunch of videos and tutorials and one thing I've noticed is that they are all using localhost or 127.0.0.1 for demonstration purposes. 
However, one thing I'm missing out is actually figuring out how to work with the domains. 
In my case, I'm using Valet to serve the laravel app. And after configuring everything needed for sanctum, I'm left struggling with getting the CSRF cookie when request is sent to https://domain.test/sanctum/csrf-cookie. 

In Postman I'm getting no cookies 
![alt text](https://i.imgur.com/JO6S75M.png "CSRF Cookie request for domain")

I started going nuts, and then I tried simple `php artisan serve` and made a request to `http://127.0.0.1:8000/sanctum/csrf-cookie` and by magic I got the cookies

![alt text](https://i.imgur.com/eDHaEtP.png "CSRF Cookie request for 127.0.0.1")

Any explanation why this might happen will be great. 

To note, I've set SESSION_DOMAIN and SANCTUM_STATEFUL_DOMAINS in my env file to include both localhost and domain.test.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
