### ISSUE TITLE
pipe character in the 'plaintextToken'

### ISSUE THREAD

**Issue by rabol** [laravel/sanctum#140]
- Sanctum Version: 2.3.0
- Laravel Version: 7.10.3
- PHP Version: 7.4.5
- Database Driver & Version:

### Description:
The plaintextToken is no longer a token, but a 'combination' of id and the token

Problem is that if the plain text token is used as shown, the user will pass a wrong token in all requests

### Steps To Reproduce:

Create a new token
look at the value in the plainTextToken property

e.g

$tokenName = Str::slug(env('APP_NAME'));
$newAccessToken = $user->createToken($tokenName);
Log::info($newAccessToken->plainTextToken);

**Comment by themsaid** [comment]
Hey,

I don't seem to understand your issue. Do you get an error message? Does your app not accept the new token? Can you please elaborate?

**Comment by driesvints** [comment]
That's intended, the combination of the id and the token is for more performant lookups. It'll also work if you only use the plain text token but together you'll get a more performant lookup.

**Comment by rabol** [comment]
I'm not sure that it correct

Here is a test the support my argument:

Steps to do the test - Im using a Homestead on my mac:

laravel new test
composer require laravel/ui
php artisan ui bootstrap --auth
npm install && npm run dev
composer require laravel/sanctum
php artisan vendor:publish --provider="Laravel\Sanctum\SanctumServiceProvider"
<modify .env>
php artisan make:controller TestController -i
< add route to web.php>
< add 'button' to welcome.php>
create test_result.blade.php
php artisan make:model TestData -m
< add two string fields combo, plain>
php artisan migrate
launch site
launch the test


The code of the TestController:


```
<?php

namespace App\Http\Controllers;

use App\TestData;
use App\User;
use Illuminate\Http\Request;
use Faker\Factory as Faker;
use Laravel\Sanctum\PersonalAccessToken;

class TestController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        // Delete all users
        User::truncate();

        // Create new users
        factory(User::class, 50)->create();

        // create tokens
        $users = User::all();

        foreach ($users as $user)
        {
            $newToken = $user->createToken(env('APP_NAME'));
            $newToken->plainTextToken;

            [$id, $token] = explode('|', $newToken->plainTextToken, 2);

            TestData::create([
                'combo' => $newToken->plainTextToken,
                'plain' => $token,
            ]);
        }

        // Get random users:
        $testDataRecords = TestData::all()
            ->random(25);

        $comboStart = microtime(true);

        /* Start of the code to profile */
        // combo
        foreach ($testDataRecords as $testDataRecord)
        {
            PersonalAccessToken::findToken($testDataRecord->combo);
        }
        $comboEnd = microtime(TRUE);

        // plain
        $plainStart = microtime(true);
        foreach ($testDataRecords as $testDataRecord)
        {
            PersonalAccessToken::findToken($testDataRecord->plain);
        }
        $plainEnd = microtime(true);
        /* End of the code to profile */

        // Previous
        $prevStart = microtime(true);
        foreach ($testDataRecords as $testDataRecord)
        {
            PersonalAccessToken::where('token', hash('sha256', $testDataRecord->plain))->first();
        }
        $prevEnd = microtime(true);

        return view('test_result')
            ->with('combostart',$comboStart)
            ->with('comboend', $comboEnd)
            ->with('plainstart', $plainStart)
            ->with('plainend',$plainEnd)
            ->with('prevstart', $prevStart)
            ->with('prevend',$prevEnd);
    }
}

```


no matter how many times I execute the test, the 'old' way is faster and using the 'plain' token without pipe is slower, because it needs to check if there is a pipe character.

sample result:


```
Combo 0.028832912445068 seconds to complete.
Plain 0.029609203338623 seconds to complete.
Previous 0.02697491645813 seconds to complete.

```

**Comment by themsaid** [comment]
of course the extra code needs more time to run. The idea is to speed the database lookup which is the bottlenech.

**Comment by rabol** [comment]
Which is my point, there is no performance gain in the new version.
There is no difference in looking up by Id or By Token as both have unique indexes

**Comment by themsaid** [comment]
Lookup using an incremental integer is faster than lookup using a string even when both indexed.

In all cases you can opt out of this behaviour if you prefer to lookup using a string and the DB isn't a bottleneck in your case. You can extend the Token model and change the behaviour.

**Comment by telkins** [comment]
Hi all (@themsaid @driesvints @rabol),

I'm not going to get into the argument over which way is faster....I just want one thing clarified: Are we supposed to show users the entire `ID|token` value or are we to strip the `ID|` and show them just `token`?

It looks like it will work either way, but it seems odd that we would be sharing the actual ID.  There are some -- like me -- that are a little uncomfortable with this.

Anyway, your input is welcome and appreciated.  Thanks.  :-)

**Comment by telkins** [comment]
Oh...just a quick addition...one more reason to bee uncomfortable with sharing the ID, as it reveals a bit about what's going on in the app/DB, but also because it binds the user's token to the `id` field value.

Neither of these things are, in and of themselves, major issues IMHO, but they still seem like things to be avoided if possible.

Again, not looking to argue....just looking for some of you guys to help me feel a little more certain that I'm doing things the right way.  :-)

**Comment by driesvints** [comment]
It's indeed meant that you show the full `id|token` but you can just show `token` if you're more comfortable with that. Both will work but `id|token` will provide a speedy lookup.

**Comment by telkins** [comment]
> It's indeed meant that you show the full `id|token` but you can just show `token` if you're more comfortable with that. Both will work but `id|token` will provide a speedy lookup.

Thx.
