### ISSUE TITLE
token with id

### ISSUE THREAD

**Issue by hmdshariati** [laravel/sanctum#143]
https://github.com/laravel/sanctum/blob/3a06f9950f22698b07c6b05052d33c5520ff22e5/src/HasApiTokens.php#L52 
according to line above when I want create new token , it return me token with ID but it another computer it return without id. 
when I test Bearer token with id it faild but when I remove id it works.
why the id attached to token?
`=> Laravel\Sanctum\NewAccessToken {#4592
     +accessToken: Laravel\Sanctum\PersonalAccessToken {#4681
       name: "test",
       abilities: "["*"]",
       tokenable_id: 2,
       tokenable_type: "App\User",
       updated_at: "2020-05-18 07:54:16",
       created_at: "2020-05-18 07:54:16",
       id: 63,
     },
     +plainTextToken: "63|rWkz6zVJrdb6sHcc3gyotazsroTelysKbRFPFtpcsmE2NC9R50LakS4kZS5YrnAh7b4UkcddZRPsicsL",
   }
`

**Comment by driesvints** [comment]
Please see https://github.com/laravel/sanctum/pull/136

**Comment by atva-dev** [comment]
So should we remove the id in our code? The docs probably need to state this?

**Comment by driesvints** [comment]
Yes

**Comment by rvanbaalen** [comment]
So, Laravel Sanctum tokens look like this:

`6|htop_YpsYfFRCQ5VLYv8yNY0he9pEDcwNpdkwvlkcrrk5e2600637`

Including the `6|` prefix? That's by design and that is the full token that's supposed to be communicated to the user? I find it odd that a database ID is exposed like this.
