### ISSUE TITLE
Dynamic guard change for spa authorization

### ISSUE THREAD

**Issue by sergey-yabloncev** [laravel/sanctum#144]
If the project uses multiple guards, for example web and admin, you can't use spa authorization for multiple guards. 

This feature is provided for authorization via token.

https://github.com/laravel/sanctum/blob/2.x/src/Guard.php#L45
https://github.com/laravel/sanctum/blob/2.x/src/SanctumServiceProvider.php#L95

I would like to be able to set a guard in middleware, to use a similar design

```php
Route::middleware(['auth:sanctum'])->get('/user', function () {
    return auth('web')->user();
});

// and in one project

Route::middleware('auth:sanctum')->get('/admin', function () {
    return auth('admin')->user();
});
```

**Comment by driesvints** [comment]
If you want to implement something like this just send in a pr. Thanks.

**Comment by lnpbk** [comment]
@sergey-yabloncev did you manage to implement this, or begin working on anything?

**Comment by sergey-yabloncev** [comment]
> @sergey-yabloncev did you manage to implement this, or begin working on anything?

@lnpbk unfortunately, no. I refused to use the package as a SPA Authentication, I used it as the Tokens API. Additionally, by adding custom middleware checking the instanceof model of the authorized user

for example

```php

<?php

namespace App\Http\Middleware;

use App\Models\User\Admin;
use Closure;

class VerifyAdmin
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (!(auth()->user() instanceof Admin)) {
            abort(403);
        }

        return $next($request);
    }
}
```
App\Http\Kernel.php

```php
<?php

namespace App\Http;
//...
use App\Http\Middleware\VerifyAdmin;
use App\Http\Middleware\VerifyUser;

class Kernel extends HttpKernel
{
//...
    protected $routeMiddleware = [
        //...
        'admin' => VerifyAdmin::class,
        'user' => VerifyUser::class,
    ];
}
```
use in route or controller

```php
Route::middleware(['auth:sanctum', 'admin'])
```

**Comment by IlCallo** [comment]
If you accept to avoid config caching, you can use a middleware to change it at runtime.

```php
// app/Http/Middleware/UpdateSanctumConfigForCentralApp.php

<?php

namespace App\Http\Middleware;

use Closure;

class UpdateSanctumConfigForCentralApp
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        // Without this, remember_me feature could break 
        //  using the wrong cookie if guards use different user models/tables
        config(['auth.defaults.guard' => 'another_guard']);
        // THIS WILL WORK ONLY IF CONFIG ISN'T CACHED
        config(['sanctum.guard' => 'another_guard']);
        return $next($request);
    }
}
```

You should then update the `Kernel` to ensure this middleware is always applied before the Sanctum one

```php
// app/Http/Kernel.php

    /**
     * The priority-sorted list of middleware.
     *
     * This forces non-global middleware to always be in the given order.
     *
     * @var array
     */
    protected $middlewarePriority = [
        \App\Http\Middleware\UpdateSanctumConfigForCentralApp::class,
        \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
    ];
```

And lastly add it to the API routes you want to use another guard 

```php
// routes.api.php

    Route::middleware(['auth:sanctum'])->group(function () {
       // Routes using normal guard 
       Route::group(function () {
         // ..
       });

       // Routes using the other guard
       Route::middleware(UpdateSanctumConfigForCentralApp::class)->group(function () {
         // ..
       });
    });
```

**Comment by ivand88** [comment]
@sergey-yabloncev - Your approach works just fine and I used it for the project I'm currently working on.

I had much issues trying to run the tests. Most of the time when I want to inspect if I'm allowed to reach some sanctum guarded routes, while logged in with some session-based guards, I got status code 200, when I expect 401.

Just for example:

Guards configuration:
![image](https://user-images.githubusercontent.com/18655454/113629728-1a2eba80-9667-11eb-82c5-ebd901ad0746.png)

Testing:
![image](https://user-images.githubusercontent.com/18655454/113629461-bad0aa80-9666-11eb-9576-e2fb0f180e60.png)

When I try to reach this route, I get status code 200.
![image](https://user-images.githubusercontent.com/18655454/113629521-d045d480-9666-11eb-8708-3e821b18f750.png)

So thank you for sharing your approach. 🍻

**Comment by cja-github** [comment]
@sergey-yabloncev Thank you for your example code. It was exactly what I needed.

**Comment by RahulDey12** [comment]
@ivand88 Tests wont work with acting as because sanctum is looks for api token and the `tokenable_type` with acting as u are just bypassing autentication

**Comment by t8ysn** [comment]
> @sergey-yabloncev - Your approach works just fine and I used it for the project I'm currently working on.
> 
> I had much issues trying to run the tests. Most of the time when I want to inspect if I'm allowed to reach some sanctum guarded routes, while logged in with some session-based guards, I got status code 200, when I expect 401.
> 
> Just for example:
> 
> Guards configuration:
> ![image](https://user-images.githubusercontent.com/18655454/113629728-1a2eba80-9667-11eb-82c5-ebd901ad0746.png)
> 
> Testing:
> ![image](https://user-images.githubusercontent.com/18655454/113629461-bad0aa80-9666-11eb-9576-e2fb0f180e60.png)
> 
> When I try to reach this route, I get status code 200.
> ![image](https://user-images.githubusercontent.com/18655454/113629521-d045d480-9666-11eb-8708-3e821b18f750.png)
> 
> So thank you for sharing your approach. 🍻

We’re you able to get first party SPA authentication with this? 

I was not able to get sanctums x-csrf cookie based authentication to work

**Comment by ivand88** [comment]
> @ivand88 Tests wont work with acting as because sanctum is looks for api token and the `tokenable_type` with acting as u are just bypassing authentication
> 
> Test should be like:
> 
> ```
> $admin = Admin::factory()->create();
> 
> $token = $admin->createToken('test')->plainTextToken;
> expect(DB::table('personal_access_tokens')->count())->toBe(1);
> 
> $response = $this->post('/auth/secret', [], [
>     'Authorization' => "Bearer {$token}",
> ]);
> $response->assertStatus(200);
> ```

For some other project, I've actually switched to a different 

> > @sergey-yabloncev - Your approach works just fine and I used it for the project I'm currently working on.
> > I had much issues trying to run the tests. Most of the time when I want to inspect if I'm allowed to reach some sanctum guarded routes, while logged in with some session-based guards, I got status code 200, when I expect 401.
> > Just for example:
> > Guards configuration:
> > ![image](https://user-images.githubusercontent.com/18655454/113629728-1a2eba80-9667-11eb-82c5-ebd901ad0746.png)
> > Testing:
> > ![image](https://user-images.githubusercontent.com/18655454/113629461-bad0aa80-9666-11eb-9576-e2fb0f180e60.png)
> > When I try to reach this route, I get status code 200.
> > ![image](https://user-images.githubusercontent.com/18655454/113629521-d045d480-9666-11eb-8708-3e821b18f750.png)
> > So thank you for sharing your approach. 🍻
> 
> Were you able to get first party SPA authentication with this?
> 
> I was not able to get sanctums x-csrf cookie based authentication to work

In the meantime I've actually found the resolution for my issue, explained here.

https://github.com/laravel/sanctum/pull/149

**Comment by sergey-yabloncev** [comment]
@ivand88 Thanks so much!
