### ISSUE TITLE
Broadcaster Access Denied

### ISSUE THREAD

**Issue by mehmetcansahin** [laravel/sanctum#146]
- Sanctum Version: ^2.0
- Laravel Version: ^7.0
- PHP Version: 7.2
- Database Driver & Version: mysql
- Broadcast Driver: redis

### Description:

Hello I'm trying to login to a channel with laravel echo.

I use Sanctum, I get 403 as the request response. Why do you think it might be?

### Steps To Reproduce:
api.php
```
Broadcast::routes(['middleware' => ['auth:sanctum']]);
```
api.js
```
var echo = new Echo({
  broadcaster: "socket.io",
  host: "localhost:6001",
  client: io,
  auth: {
    endpoint: '/broadcasting/auth',
    headers: {
      Authorization: "Bearer " + key,
      Referer: window.location.hostname,
    },
  },
});
```
Response;
Status | 403
```
 {
"message": "",
"exception": "Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException",
"file": "/var/www/torrentvideo/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php",
"line": 81,
"trace": [
{
"file": "/var/www/torrentvideo/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/RedisBroadcaster.php",
"line": 69,
"function": "verifyUserCanAccessChannel",
"class": "Illuminate\Broadcasting\Broadcasters\Broadcaster",
"type": "->"
}, 
...
```

**Comment by mehmetcansahin** [comment]
I realized that the cause of the problem is that I cannot see the channels originating from the api prefix I have changed. If you overwrite the web route with the api route, you need to define your channels under the api route.

**Comment by jonorozcoc** [comment]
> I realized that the cause of the problem is that I cannot see the channels originating from the api prefix I have changed. If you overwrite the web route with the api route, you need to define your channels under the api route.

How can I do that?

**Comment by hallowcard13** [comment]
> > I realized that the cause of the problem is that I cannot see the channels originating from the api prefix I have changed. If you overwrite the web route with the api route, you need to define your channels under the api route.
> 
> How can I do that?

on your routes/api.php 

`require base_path('routes/channels.php');`

**Comment by h6s8n** [comment]
if you run 

php artisan route:list 
you can find something like this:
 GET|POST|HEAD   api/broadcasting/auth ...................................................................................... Illuminate\Broadcasting › BroadcastController@authenticate
 
 so let check authenticate in BroadcastController
 
     public function authenticate(Request $request)
    {
        if ($request->hasSession()) {
            $request->session()->reflash();
        }

        return Broadcast::auth($request);
    }
    
    and then we want to check 
    auth method in this path :
    use Illuminate\Broadcasting\Broadcasters\PusherBroadcaster;


class PusherBroadcaster extends Broadcaster {
public function auth($request)
    {
        $channelName = $this->normalizeChannelName($request->channel_name);

        if (empty($request->channel_name) ||
            ($this->isGuardedChannel($request->channel_name) &&
            ! $this->retrieveUser($request, $channelName))) {
            throw new AccessDeniedHttpException;
        }

        return parent::verifyUserCanAccessChannel(
            $request, $channelName
        );
    }
    
          so as you can see we need pass this condition :
          
          (empty($request->channel_name) ||
            ($this->isGuardedChannel($request->channel_name) &&
            ! $this->retrieveUser($request, $channelName))) {
