### ISSUE TITLE
Problems with phpunit test for logout method (via token)

### ISSUE THREAD

**Issue by Dzale** [laravel/sanctum#148]
- Sanctum Version: v2.3.3
- Laravel Version: v7.13.0
- PHP Version: 7.4.3
- Database Driver & Version: SQLite in memory

### Description:
Hey guys, i've noticed a strange bug when writing unit tests for logout. I've described it in section below. 

Route actually works when you call it from Postman/Application, but test fails. Maybe i am doing something wrong ?

### Steps To Reproduce:

Method code => https://pastebin.com/fTvQVyes

Test code => https://pastebin.com/LZ7wMgeg

Response i get:
{"message":"Call to undefined method Laravel\\Sanctum\\TransientToken::delete()","errors":null}

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Dzale** [comment]
Hey @driesvints, 

thanks for quick response, ill check it out and get back to you guys, if needed.

**Comment by AlanRezende** [comment]
Hi @Dzale did you find a good solution to this?

**Comment by eskiesirius** [comment]
any update? because i searched everywhere and still no one fixed the problem

**Comment by Dzale** [comment]
Hey @AlanRezende and @eskiesirius , unfortunately i didn't find any solution. I've just decided to skip this test since it's very simple functionality

**Comment by eskiesirius** [comment]
yeah.. same..

**Comment by Andr1yk0** [comment]
Hello, found this solution. Tested only with sanctum 3.0, but should work with older versions
```
public function test_admin_logout()
{
        $user = User::factory()->create();
        Sanctum::actingAs($user); 
        $user->currentAccessToken()->shouldReceive('delete')->once();

        $res = $this->delete('/api/logout');

        $res->assertOk();
}
```

**Comment by muhammadmp97** [comment]
Thank you. @Andr1yk0 

This problem occurs during testing, because we have a TransientToken object that is different from the original token object.
