### ISSUE TITLE
EnsureFrontendRequestsAreStateful::fromFrontend() does not extract host from referer

### ISSUE THREAD

**Issue by plai2010** [laravel/sanctum#150]
- Sanctum Version: 2.3.3
- Laravel Version: 7.13.0
- PHP Version: 7.2.24
- Database Driver & Version:

### Description:
The 'sanctum.stateful' configuration (by default SANCTUM_STATEFUL_DOMAINS in .env) specifies a list of hosts/domains. However, EnsureFrontendRequestsAreStateful::fromFrontend() uses HTTP referer with "http://" and "https://" removed to match against the list. This can yield incorrect result.

### Steps To Reproduce:
False positive:
1. Set SANCTUM_STATEFUL_DOMAINS="_example.com_".
2. Access from "_example.com_**.jp**"; fromFrontend() accepts that.

False negative:
1. Set SANCTUM_STATEFUL_DOMAINS="_*.example.com_".
2. Access with HTTP referer "http://_foobar.example.com_**/**"; fromFrontend() rejects that (note ending '/' in referer).

**Comment by driesvints** [comment]
That indeed seems problematic. 

Ping @taylorotwell

**Comment by RahulDey12** [comment]
I've added a PR regarding this problem
