### ISSUE TITLE
Auth::check() return true on Controllers, but false on Request

### ISSUE THREAD

**Issue by r94ever** [laravel/sanctum#152]
- Sanctum Version: 2.3.3
- Laravel Version: 7.12.0
- PHP Version: 7.2.29
- Database Driver & Version: MySQL 5.7

### Description:
`Auth::check()` return `true` on **Controllers**, but `false` on **Request**

### Steps To Reproduce:
This is my Controller content: the logger always return correct user's id

```
public function __invoke(UpdateProfileRequest $request)
{
    logger($request->user()->id);  // return 1 --> correct
    logger(Auth::id());  // return 1 --> correct
    logger(Auth::guard('web')->id());  // return 1 --> correct

    DB::transaction(function () use ($request) {
        $this->userRepository->update($this->request->validated(), Auth::id());

        $this->userRepository->sync(
            Auth::id(),
            'wards',
            $this->request->input('ward.id')
        );
    });

    return success_response("Hồ sơ của bạn đã được cập nhật");
}
```

This is my request file: The auth check method alway return false

```
class UpdateProfileRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return Auth::guard()->check();  // or Auth::guard('web')->check() or Auth::guard('web')->check()
    }
}
```

**Comment by RahulDey12** [comment]
How ? Let me check this

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by r94ever** [comment]
Okey I will ask on community forums. Thanks
