### ISSUE TITLE
returning unauthenticated after upgrade from version 2.3.1 to 2.4.0

### ISSUE THREAD

**Issue by iteniasim** [laravel/sanctum#161]
Old version
- Sanctum Version: 2.3.1

New version (problematic)
- Sanctum Version 2.4.0

### Description:

sanctum returns token and passes through the login method without any problem, but after that it still gives unauthenticated response on version 2.4.0 when i am replicating exactly the same steps.

reverting back to version 2.3.1 again solves the probelm.

this might be a bug or if not please tell me what is the cause of this.

### Steps To Reproduce:

- create new laravel app and serve it at **api.domain.test**
- create client vue app and serve it at **domain.test**
- install laravel ui and its auth scaffold
-install laravel sanctum and publish its assets
-php artisan migrate

- in env add the following
**SESSION_DOMAIN=domain.test
SANCTUM_STATEFUL_DOMAINS=domain.test**

-in cors config
**'supports_credentials'     => true,
'paths'                    => ['api/*', '/sanctum/csrf-cookie', 'login', 'logout'],**

- in vue main.js 
**axios.defaults.withCredentials = true;
axios.defaults.baseURL = "http://api.domain.test/";**

-create a simple form with input credentials
submit the form like so
`this.$axios.get("sanctum/csrf-cookie").then(() => {
        this.$axios
          .post("login", { email: this.username, password: this.password })
          .then(
            () => {
              this.user();
            },
            error => {
              this.loading = false;
              this.message = error.response.data.message;
            }
          );
      });`

proper token is returned and set in cookie,
login also succeeds
but the user info is not returned with that api.

and, yeah, i changed the guard in the api,
`Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return $request->user();
});`

and once again,
**going back to version 2.3.1 fixes everything following these steps**

**Comment by iteniasim** [comment]
i tried out each version, so apparently the problem is in the latest version update from 2.3.3 to 2.4.0

**Comment by RahulDey12** [comment]
Do you sending the bearer token

**Comment by driesvints** [comment]
Is this the same issue as https://github.com/laravel/sanctum/issues/159 ? Are you running your front-end on a specific port? Does it work if you add the port to `SANCTUM_STATEFUL_DOMAINS=domain.test`?

**Comment by camiant** [comment]
@driesvints 
good catch! I've solved adding port number after domain
`SANCTUM_STATEFUL_DOMAINS=domain.test:XXXX`

thanks a lot!

**Comment by driesvints** [comment]
Gonna close this as a duplicate then.

**Comment by iteniasim** [comment]
Yes, that was the problem.

**Comment by GabrielQA** [comment]
> Sí, ese era el problema.

Seguiste los pasos? yo igual pero no me funcionó

**Comment by sergeevpasha** [comment]
omg thx, spent 2 hours to manage that it was just a port =D

**Comment by MmadiZaib** [comment]
@driesvints thanks, It's saved me a lot of time.
