### ISSUE TITLE
Customizing Sanctum Middleware

### ISSUE THREAD

**Issue by MarioVillani** [laravel/sanctum#162]
Hello,
I'm wondering if there is a way to get a customized Sanctum middleware.

For example, take this route:

	Route::group(['middleware' => ['auth:sanctum']], function () {
        	Route::post('/exampleRoute', 'Auth\APIController@exampleFunction');
    });	

If token is not valid, i'm getting redirected on base URL of my project. What i need is to simply output a JSON message with statuscode 500, saying that given token is not valid.
Since Sanctum is made for APIs, would be better to add a config parameter that could enable this kind of behaviour?
Thanks.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by dducro** [comment]
Did you supply the accepts: application/json header to the request?

**Comment by MarioVillani** [comment]
Yes, by giving explicit `Accept: application/json` header it gives me a JSON response, setting `Content-Type: application/json` i get the redirect.
I was asking how to create a custom Sanctum middleware because i need to force to give always a JSON response, regardless the `Accept` header, and i also need to perform extra actions in the middleware.

**Comment by dducro** [comment]
In that case you can just modify `App\Http\Middleware\Authenticate`
Here you can extend auth login, and return a custom response.
Hope it helps.

**Comment by laurence702** [comment]
> In that case you can just modify `App\Http\Middleware\Authenticate`
> Here you can extend auth login, and return a custom response.
> Hope it helps.

Hello @dducro  please do you mind expatiating on this. I'm trying to customize the error with a full JSON response of my choice. right now i just get a single message as the screenshot below shows. could you share a snippet of how to achieve this in Authenticate.php as you've suggested.  thanks in anticipation

<img width="1280" alt="Screenshot 2021-05-31 at 09 14 18" src="https://user-images.githubusercontent.com/30216553/120162524-63773280-c1f0-11eb-9ed5-d0fdf016dea7.png">

**Comment by dducro** [comment]
@laurence702 In your case, if you only want to return a different json response when unauthenticated.
I would recommend to override `unauthenticated` in `App\Exceptions\Handler` by adding the following.
Here you can return a custom json response with more data then just a message, hope it helps.

```
/**
     * Convert an authentication exception into a response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Auth\AuthenticationException  $exception
     * @return \Symfony\Component\HttpFoundation\Response
     */
    protected function unauthenticated($request, AuthenticationException $exception)
    {
        return $request->expectsJson()
                    ? response()->json(['message' => $exception->getMessage()], 401)
                    : redirect()->guest($exception->redirectTo() ?? route('login'));
    }
```

**Comment by vicsystems55** [comment]
> Did you supply the `Accept: application/json` header to the request?
this i was my issue. i was using postman, Larave 7

**Comment by bsienn** [comment]
Sorry for hijacking, but its related. Can some please shine some light on this similar problem i've

```
Route::middleware(['ForceJson'])->group(function () {
    Route::post('/api-login', [APIManager::class, 'api_login']);

    Route::middleware(['auth:sanctum'])->group(function () {
        Route::get('/user', function (Request $request) {
            return $request->user();
        });
});

Middleware/ForceJson.php

class ForceJson
{
    public function handle(Request $request, Closure $next)
    {
        // Force Json accept type
        if (! Str::contains($request->header('accept'), ['/json', '+json'])) {
            $request->headers->set('accept', 'application/json,' . $request->header('accept'));
        }

        return $next($request);
    }
}
```

The ForceJson works fine for the `/api-login` route and if there is no header it add manually, But `/user` route under `auth:sanctum` do not return json as if the `ForceJson` middleware is not running at all.

Without modifying any `unauthenticated` method call, this approach seems useful to me, is there any reason for the above to not work, or is there any alternative way to achieve the force json behavior?

please delete this msg if its not appropriate here.

**Comment by dducro** [comment]
@bsienn You should use middleware priority to make sure your middleware is run before auth.
See: https://laravel.com/docs/8.x/urls#url-defaults-middleware-priority
auth is usually run very early on in the stack, before other middleware.

**Comment by bsienn** [comment]
OMG, That worked, Thank you for the quick response. I recall I did read it a couple of years back once(Post corona). Hence I forgot as I was away from Laravel till now. Kudos

**Comment by hemendraajmera** [comment]
I have two API route like
api/v1/customers/profile

**Comment by ccec1t91077** [comment]
Just want to express some of my opinion, I agree what @MarioVillani says.

The api should force json response instead of redirect, and the how it response json or redirect is depend on an accept header, it's weird. Response type shouldn't be depend's on an header, we never trust if client send header or not, and I don't want to make another middleware for just add header.

I'm not saying there's an issue in sanctum, it's just I expect that sanctum should have a custom middleware itself instead of the default auth.

How I solved is like @dducro said, modify the default auth  `App\Http\Middleware\Authenticate`, always return null in api routes：
```php
// Example in Laravel 10
class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     */
    protected function redirectTo(Request $request): ?string
    {
        return ($request->is('api/*') || $request->expectsJson()) ? null : route('login');
    }
}
```

**Comment by ARehmanMahi** [comment]
People having problem with APIs returning non-json response, give the following a try making use of `ForceJsonResponse::class` in the api middleware array. No changes in auth or anything else, default laravel.

**ForceJsonResponse::class**
```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class ForceJsonResponse
{
    /**
     * Handle an incoming request.
     */
    public function handle(Request $request, Closure $next): mixed
    {
        $request->headers->set('Accept', 'application/json');

        return $next($request);
    }
}
```

**app/Http/Kernel.php**
```
 protected $middlewareGroups = [
        'web' => [
            ...
        ],

        'api' => [
            ForceJsonResponse::class,
            ...
        ],
    ];

```

**Comment by acharseth** [comment]
@ARehmanMahi , did you also have to change the order for `$middlewarePriority`? Could you show how?

**Comment by ARehmanMahi** [comment]
> @ARehmanMahi , did you also have to change the order for `$middlewarePriority`? Could you show how?

No, as I mentioned in my previous comment, no changes at all. Just default laravel settings plus this middleware in the API group.

**Comment by ccec1t91077** [comment]
Hi @acharseth, asume your `$middlewarePriority` is working, if you follow my solution, you'll edit the `App\Http\Middleware\Authenticate`, but in your `$middlewarePriority` is using the  `\Illuminate\Auth\Middleware\Authorize` try to remove the `Illuminate` namespace.

**Comment by some0ne2** [comment]
> People having problem with APIs returning non-json response, give the following a try making use of `ForceJsonResponse::class` in the api middleware array. No changes in auth or anything else, default laravel.
> 
> **ForceJsonResponse::class**
> 
> ```
> <?php
> 
> namespace App\Http\Middleware;
> 
> use Closure;
> use Illuminate\Http\Request;
> 
> class ForceJsonResponse
> {
>     /**
>      * Handle an incoming request.
>      */
>     public function handle(Request $request, Closure $next): mixed
>     {
>         $request->headers->set('Accept', 'application/json');
> 
>         return $next($request);
>     }
> }
> ```
> 
> **app/Http/Kernel.php**
> 
> ```
>  protected $middlewareGroups = [
>         'web' => [
>             ...
>         ],
> 
>         'api' => [
>             ForceJsonResponse::class,
>             ...
>         ],
>     ];
> ```

This works fine. Do you have any idea how to force a rate limit rule to run before the `auth` part?
Doing it the same way as you did and reference it directly inside the `api` middlewareGroups doesn't help here.

**Comment by bsienn-khan** [comment]
@some0ne2 have a look https://github.com/laravel/sanctum/issues/162#issuecomment-1860401328

you should be able to achieve that by changing middleware priority.

**Comment by some0ne2** [comment]
Dear @ARehmanMahi I was able to get it running by using this inside `Kernel.php`.
Just for me to understand, can you explain, why it works fine by using a custom middleware which is NOT defined in `middlewarePriority`, but listed inside the `middlewareGroups` like f.e.

```
 protected $middlewareGroups = [
        'web' => [
            ...
        ],

        'api' => [
            aCustomMiddleware::class,
            ...
        ],
    ];
```

But for rate limiter it's not possible to run before `sanctum:auth` if I won't change order here (using `ThrottleRequestsWithRedis` class to rate limit):

    protected $middlewarePriority = [

        \Illuminate\Foundation\Http\Middleware\HandlePrecognitiveRequests::class,
        \Illuminate\Cookie\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \Illuminate\Routing\Middleware\ThrottleRequestsWithRedis::class,
        \Illuminate\Contracts\Auth\Middleware\AuthenticatesRequests::class,
        \Illuminate\Routing\Middleware\ThrottleRequests::class,
        \Illuminate\Contracts\Session\Middleware\AuthenticatesSessions::class,
        \Illuminate\Routing\Middleware\SubstituteBindings::class,
        \Illuminate\Auth\Middleware\Authorize::class,
    ];

**Comment by bsienn-khan** [comment]
@some0ne2 im not sure what you mean but, plus this is not a place to discuss features. Please post your question in appropriate platform like stackoverflow laravel forums.

Laravel discord chat is a good place as well
