### ISSUE TITLE
Auth::logout()  Fills user deleted_at.

### ISSUE THREAD

**Issue by omidd1315** [laravel/sanctum#164]
- Sanctum Version: 2.3.4
- Laravel Version: 7.0.0
- PHP Version: 7.3
- Database Driver & Version: MariaDB-1:10.4.13

### Description:
when use Auth::logout() in my AuthController make the user soft delete.

### auth.php
```
 'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
 'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
            'hash' => false,
        ],
    ],```


using Auth::guard('web')->logout() but again make user deleted.

**Comment by RahulDey12** [comment]
It is not passport repo

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
