### ISSUE TITLE
Documentation for same folder project

### ISSUE THREAD

**Issue by ianrussel** [laravel/sanctum#165]
Currently I have a project that have reactjs inside laravel folder in resources/js.The docs does not specify how to configure sanctum for this scenario.I tried this for hours by reading the sanctum docs but still no luck. How do you configure sanctum if for example your reactjs is in same domain? (laravel.test/admin) -> where react js is being access, (laravel.test/admin/V1)-> where the api lives.laravel.test/ will redirect to laravel.test/admin. I can successfullly login and cookies (XSRF, and laravel _session) is sent in response, but accessing protected routes results in 401.

My stateful domains looks like this

`laravel.test/admin`

And my SESSION_DOMAIN i tried following interchangeably
`laravel.test`
`.laravel.test`
`laravel.test/admin/V1`
`.laravel.test/admin/V1`

But none works

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
