### ISSUE TITLE
Sanctum::ActingAs Cant Logout

### ISSUE THREAD

**Issue by gofish543** [laravel/sanctum#167]
- Sanctum Version: Latest
- Laravel Version: Latest
- PHP Version: Latest
- Database Driver & Version: MySQL Latest

### Description:
I have a test case
```php
$this->loginAsEmployee();
$this->get(route('api.employees.index'))
    ->assertOk()
    ->assertJsonStructure([
        'data' => [
            ['id', 'user' => ['full_name']]
        ]])
    ->assertJsonCount(1 + 10, 'data')
    ->assertJsonFragment([
        'id' => $employees->first()->id,
        'full_name' => $employees->first()->user->full_name,
    ]);

$this->loginAsEmployee();
$this->get(route('api.employees.index', [
    'page' => '1',
    'per_page' => '10'
]))->assertOk()
    ->assertJsonStructure([
        'status',
        'data' => [
            'data',
            // Just a few pagination keys to make sure it was paginated
            'next_page_url',
            'prev_page_url',
        ]
    ])->assertJson([
        'data' => [
            'per_page' => 10,
        ]
    ]);

$this->loginAsShooter();
$this->get(route('api.employees.index'))
    ->assertForbidden();
```

My LoginAs functions are below
```php
/**
 * @param mixed|null $role
 * @return $this
 */
protected function loginAsEmployee($role = null) {
    if ($role) {
        $this->authEmployee->update([
            'role' => $role
        ]);
    }
    $this->logout();

    Sanctum::actingAs($this->authEmployee->user,[], 'web');
//        $this->actingAs($this->authEmployee->user); WORKS!!!!!

    return $this;
}

/**
 * @return $this
 */
protected function loginAsCoach() {
    $this->logout();

    Sanctum::actingAs($this->authCoach->user,[], 'web');
//        $this->actingAs($this->authCoach->user); WORKS!!!!!

    return $this;
}

/**
 * @return $this
 */
protected function loginAsShooter() {
    $this->logout();

    Sanctum::actingAs($this->authShooter->user,[], 'web');
//        $this->actingAs($this->authShooter->user); WORKS!!!!!

    return $this;
}

/**
 * @return $this
 */
protected function logout() {
    Auth::guard('web')->logout();

    return $this;
}
```

The problem is, Sanctum::actingAs is not setting the new user on call. It will use the first user set and never update it. Even after calling `logout()` and trying session clears, etc.

The regular `$this->actingAs(...)` works, but something with Sanctum's does not.

**Comment by driesvints** [comment]
Which guard is protecting your routes?

**Comment by gofish543** [comment]
Here is a slimmed down version of my api.php
```php
<?php

Route::prefix('api')->namespace('Api')->group(function () {
    Route::middleware([])->group(function () {
         // ... More stuff here that is irrelivent
    });

    Route::middleware(['auth:sanctum', 'verified'])->group(function () {
        // ... More stuff here that is irrelivent
    });
});
```

**Comment by driesvints** [comment]
You're confusing the sanctum guard with the web guard. The web guard is for when a user has already been authenticated in your app. The sanctum guard is for protecting your API routes with tokens.

Please try a support channel if you have further questions:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by gofish543** [comment]
In order for the "logout" to be applied properly, anywhere in any action that uses request()->user($guard) a guard must manually be passed in as request()->guard('web')... Leaving the guard empty will cause a fallback to the first logged in user rather than the user that is currently logged in.
I believe this is a bug, how can we get this issue more closely identified and potentially patched?
