### ISSUE TITLE
Model find<Column> not working

### ISSUE THREAD

**Issue by socramjunio2** [laravel/sanctum#171]
Good afternoon, when the database has more than one token item, this findToken does not work.

https://github.com/laravel/sanctum/blob/73eb9c1070a82e09f2c7edadcd21ba3102def1aa/src/Guard.php#L63

![image](https://user-images.githubusercontent.com/21258161/87969628-e68c1000-ca98-11ea-95d7-bcc26e920718.png)

**Comment by socramjunio2** [comment]
Hello ?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by socramjunio2** [comment]
Dude, it's not a question. I don't understand the lack of understanding.

This form of model calling does not work properly, its behavior is abnormal.

If I had any questions I wouldn't open an issue for that.

But dear man, it is buggy for me, I will wait for more people to report the same thing for you to give due importance.

But I'm not just a buddy who uses Taylor's free tools,

I use the new laravel, envoyer, forge, steam and several other tools and it seems that almost every time I try to report a bug / error of that.

sincerity, it discourages me to continue with this company's products.
