### ISSUE TITLE
Target class [App\\Http\\EnsureFrontendRequestsAreStateful] does not exist.

### ISSUE THREAD

**Issue by AlexSunlight** [laravel/sanctum#173]
- Sanctum Version: 2.4.2
- Laravel Version: 7.20.0
- PHP Version: 7.2.19
- Database Driver & Version:
mysql 14.14
### Description:
After authorization, I try to send a GET request
http://127.0.0.1:8000/api/user
but in the end I get the error
 ` Target class [App \\ Http \\ EnsureFrontendRequestsAreStateful] does not exist.`
[Screenshot with error ](https://imgur.com/a/yJmr82F)
### Steps To Reproduce:
I have configured authorization for Laravel through Sanctum SPA via official [guide](https://laravel.com/docs/7.x/sanctum )
I also have a React client application. Everything works great.
Now I am testing authorization via POSTMAN.
I set it up as described here https://www.youtube.com/watch?v=YavzhzhzhksfLTo
Request for / login works successfully and I get XSRF-TOKEN.
After authorization, I try to send a GET request
http://127.0.0.1:8000/api/user
but in the end I get the error
 ` Target class [App \\ Http \\ EnsureFrontendRequestsAreStateful] does not exist.`
Then I searched for the answer on google but couldn't find anything.

**Comment by driesvints** [comment]
Seems like you're referencing this class without importing it through its correct namespace. 

Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by AlexSunlight** [comment]
this is my api.php
```
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
```

**Comment by AlexSunlight** [comment]
this is my Kernel.php
```
'api' => [
            EnsureFrontendRequestsAreStateful::class,
            'throttle:60,1',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
```

What I am doing wrong?

**Comment by AlexSunlight** [comment]
Why did you close the issue? Problem not solved...

**Comment by AlexSunlight** [comment]
Problem solved by adding to Kernel.php
`use Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful;`

**Comment by amrikarisma** [comment]
Some issue on Laravel 8 
```
Illuminate\Contracts\Container\BindingResolutionException
Target class [Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful] does not exist.
```
kernel.php
`<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;
use Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful;

....

        'api' => [
            EnsureFrontendRequestsAreStateful::class,
            'throttle:60,1',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
`

**Comment by amrikarisma** [comment]
> Problem solved by adding to Kernel.php
> `use Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful;`

I have done everything but it still doesn't work.

**Comment by amrikarisma** [comment]
Problem solved. I tried to install again and it worked. Lol.

```
mbp@mbps-MacBook-Pro siemon-api % php artisan vendor:publish --provider="Laravel\Sanctum\SanctumServiceProvider"
Unable to locate publishable resources.
Publishing complete.
mbp@mbps-MacBook-Pro siemon-api % composer require laravel/sanctum

Using version ^2.6 for laravel/sanctum
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing laravel/sanctum (v2.6.0): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/sanctum
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
mbp@mbps-MacBook-Pro siemon-api % php artisan vendor:publish --provider="Laravel\Sanctum\SanctumServiceProvider"
Copied Directory [/vendor/laravel/sanctum/database/migrations] To [/database/migrations]
Copied File [/vendor/laravel/sanctum/config/sanctum.php] To [/config/sanctum.php]
Publishing complete.
mbp@mbps-MacBook-Pro siemon-api %
```

**Comment by hugorax** [comment]
Problem solved in my case:

composer update

in kernel.php

'api' => [
            \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
....]


and then
php artisan vendor:publish --provider="Laravel\Sanctum\SanctumServiceProvider"
