### ISSUE TITLE
This Set-Cookie was blocked after send request sanctum/csrf-cooki

### ISSUE THREAD

**Issue by hungnv234** [laravel/sanctum#175]
- Sanctum Version: v2.4.2
- Laravel Version: 7.24.0

### Description:
When I try use Vue SPA call api to Laravel server, I got response with Set-Cookie but browser (Chrome) can't set cookie.

![Screen Shot 2020-08-11 at 17 24 19](https://user-images.githubusercontent.com/26863405/89886900-9582be00-dbf7-11ea-80bb-3c1c8afdce1f.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
