### ISSUE TITLE
401 unauthenticated get csrf-cookie

### ISSUE THREAD

**Issue by Nemes1sX** [laravel/sanctum#176]
- Sanctum Version: 2.0
- Laravel Version: 7.x
- PHP Version: 7.3.x
- Database Driver & Version:

### Description:

401 unauthenticated, when trying to get csrf-cookie 
### Steps To Reproduce:
401 unauthenticated, when trying to get csrf-cookie. First I register the user, later on automatically login him and I get an error.  Please, how to solve this issue
### Code:
UserController.php
```
public function createUser(Request $request)
    {

        $validation = Validator::make($request->all(), [
            'name' => 'required|string|regex:/(^(a-zA-Z\s))*$/|unique:users',
            'email' => 'required|email|unique:users',
            'password'  => 'required|min:8|max:20|confirmed',
        ]);
        if ($validation->fails())
        {
            return response()->json([
                'status' => 'error',
                'errors' => $validation->errors()
            ], 422);
        }
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->save();

       $this->guard('web')->login($user);



        return response()->json(['status' => 'success', 'user' => $user], 200);

    }
```
Register.vue
```
    registerUser()
        {
            this.errors = [];
            if(!this.validation().length){
                this.axios
                    .post('http://local.requestmapper.com/api/user/register', this.user)
                    .then( response =>{
                        axios.get('/sanctum/csrf-cookie')
                              .then(response => {
                                this.$router.push({name: 'user.organization'})
                              });
                    })
                .catch(error => console.log(error))
                .finally(() => this.loading = false)
            }
            else return this.errors;
          }
    }
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
