### ISSUE TITLE
Is it possible to reuse token so it won't need to keep creating new token when user login

### ISSUE THREAD

**Issue by sooxt98** [laravel/sanctum#177]
Maybe there's a way to generate a master token that could reuse every time

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by sooxt98** [comment]
Hi @driesvints, this is a feature request that I hope this library could implement instead of issue reporting / how-to question.
