### ISSUE TITLE
Responses return 401 errors

### ISSUE THREAD

**Issue by hexaez** [laravel/sanctum#190]
- Laravel Version: 7.27.0
- PHP Version: 7.4.3
- Database Driver & Version: 10.3.22-MariaDB-1ubuntu1 - Ubuntu 20.04

### Description:
Responses from a sanctum protected routes always return a 401 error when the encrypt property from session config is set to true

### Steps To Reproduce:

My .env variables
SESSION_DRIVER=cookie
SESSION_LIFETIME=120
SESSION_DOMAIN=localhost

My session config
'driver' => env('SESSION_DRIVER', 'file'),

'lifetime' => env('SESSION_LIFETIME', 120),

'expire_on_close' => false,

'encrypt' => true,

'domain' => env('SESSION_DOMAIN', null),

My sanctum config
'stateful' => explode(',', env('SANCTUM_STATEFUL_DOMAINS', 
  'localhost,localhost:8000,localhost:8080,127.0.0.1,127.0.0.1:8000,127.0.0.1:8080,::1')),

'expiration' => 120,

 'middleware' => [
        'verify_csrf_token' => App\Http\Middleware\VerifyCsrfToken::class,
        'encrypt_cookies' => App\Http\Middleware\EncryptCookies::class,
 ],

'prefix' => 'api'

**Comment by hexaez** [comment]
I have a separate folder for the frontend generated by Vue CLI, everything is working fine except when I set the encrypt property from session config to true and then the responses are now returning 401 errors

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
