### ISSUE TITLE
Random 404 - Not Found box showing up

### ISSUE THREAD

**Issue by marchershey** [laravel/sanctum#191]
- Sanctum Version: 2.6
- Laravel Version: 8.0
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7

### Description:
Random `404 - Not Found` Box

Taking specific steps will cause a random `404` box to appear. 

### Steps To Reproduce:
1. Visit `/user/api-tokens`
2. Create a new token (with name, obviously) & close new token window.
3. Click on `Permissions` then click `nevermind` <- important part
4. Click `Delete` and delete token.
5. Click `Create` with **NO TOKEN NAME**

![image](https://user-images.githubusercontent.com/2856490/92885263-98ccbd80-f3e0-11ea-91d8-13d86a429d60.png)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
