### ISSUE TITLE
Sanctum does not work with Laravel 8.0

### ISSUE THREAD

**Issue by alihassan1133** [laravel/sanctum#192]
- Sanctum version: ^2.2
- Laravel Version: 8.1.0
- PHP Version: 7.4.9
- Database Driver & Version: mysql Ver 15.1 Distrib 10.4.14-MariaDB

### Description:
![image](https://user-images.githubusercontent.com/62854082/92985061-2e1d8f80-f47d-11ea-9f65-c9966cdaa351.png)

I was trying to migrate an application from Laravel 7 to 8. My authentication does not work anymore. I can still log in using the form and I'm redirected, but after that I'm getting a general "unauthenticated" message. It seems like the Sanctum middleware is not picking up the fact that I have logged in.

**Comment by alihassan1133** [comment]
I just updated Sanctum version to ^2.6 but I'm still having the same issue.

**Comment by driesvints** [comment]
Please provide steps to reproduce.

**Comment by JorisDebonnet** [comment]
My issue might be different, but it sounds very similar. 

I am still on Laravel 7, but did a full `composer update` today, which triggered this same issue. I tested with several versions of this package, and have found that the issue has been introduced in laravel/sanctum:2.4.0. So I just downgraded to 2.3.3 and will keep using that for now.

My `SANCTUM_STATEFUL_DOMAINS` includes localhost,127.0.0.1, followed by a few real domains, and my SESSION_DOMAIN is unchanged (still null).

**Comment by JorisDebonnet** [comment]
I see now that an issue in 2.4.0 has led to [a change in the docs](https://github.com/laravel/docs/pull/6105/files), stating that the port needs to be included in `SANCTUM_STATEFUL_DOMAINS` (whereas, I believe, it used to be the other way around). Well, that solves my issue anyway, now version 2.6.0 works. What about you @alihassan1133, are you testing on localhost?

**Comment by alihassan1133** [comment]
@JorisDebonnet Damn. Including the port worked beautifully. Thank you.

**Comment by driesvints** [comment]
Thanks all
