### ISSUE TITLE
Issue with the behavior of actingAs during testing

### ISSUE THREAD

**Issue by sinbino** [laravel/sanctum#195]
- Sanctum Version: 2.6.0
- Laravel Version: 7.28.3
- PHP Version: 7.3.22
- Database Driver & Version: postgresql 12.4 or sqlite 3.32.1

### Description:
In one method of the phpunit test, if actingAs is executed more than once, "Auth::guard('web')->user()" returns the correct user, but "Auth::guard('sanctum')->user()" returns the wrong user ( Always return the first user).
Is this the right behavior?

### Steps To Reproduce:
https://github.com/sinbino/laravel-sanctum-issue
* Clone the above sample project.
* Run "composer install".
* Look at "app/tests/Feature/ExampleTest.php" It contains the following code.
```
$this->actingAs(\App\User::make([
    'name'  => 'USER NAME 1',
    'email' => 'user1@example.com',
]));

echo('WEB     GUARD:  USER NAME 1 = ' . (\Auth::guard('web')    ->user()->name ?? 'NOAUTH') . PHP_EOL);
echo('SANCTUM GUARD:  USER NAME 1 = ' . (\Auth::guard('sanctum')->user()->name ?? 'NOAUTH') . PHP_EOL);

$this->actingAs(\App\User::make([
    'name'  => 'USER NAME 2',
    'email' => 'user2@example.com',
]));

echo('WEB     GUARD:  USER NAME 2 = ' . (\Auth::guard('web')    ->user()->name ?? 'NOAUTH') . PHP_EOL);
echo('SANCTUM GUARD:  USER NAME 2 = ' . (\Auth::guard('sanctum')->user()->name ?? 'NOAUTH') . PHP_EOL);
```
* Run "vendor/bin/phpunit".

### Expected Results
The following is output to the console
```
WEB     GUARD:  USER NAME 1 = USER NAME 1
SANCTUM GUARD:  USER NAME 1 = USER NAME 1
WEB     GUARD:  USER NAME 2 = USER NAME 2
SANCTUM GUARD:  USER NAME 2 = USER NAME 2
```

### Actual results
The following is output to the console
```
WEB     GUARD:  USER NAME 1 = USER NAME 1
SANCTUM GUARD:  USER NAME 1 = USER NAME 1
WEB     GUARD:  USER NAME 2 = USER NAME 2
SANCTUM GUARD:  USER NAME 2 = USER NAME 1
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
