### ISSUE TITLE
How to attempt auth using user token?

### ISSUE THREAD

**Issue by rafa-acioly** [laravel/sanctum#198]
I'm receiving a POST request from a webhook that is not on my power, the only thing that i can do is to add the sanctum token on the url query of the request.

Example of the request:

```
http://myapp.com/api/endpoint/?token=VALID_SANCTUM_TOKEN
```

Middleware:
```php
    public function handle(Request $request, Closure $next)
    {

        // TODO: attempt login using the query string key "token"
        $sanctumToken = $request->query('token'); // valid sanctum token
        // Auth::attempt() does not work using "token"

        if (!$request->hasHeader(SIGNATURE_HEADER_KEY)) {
            return \response()->json([
                'error' => 'missing "x-wc-webhook-signature" header'
            ], Response::HTTP_UNAUTHORIZED);
        }

        if (!$this->hasValidSignature($request)) {
            return \response()->json([
                'error' => 'webhook-signature does not match'
            ], Response::HTTP_UNAUTHORIZED);
        }

        return $next($request);
    }
```

I cannot add "user and password" to the webhook post request and i cannot add any other header (the webhook is not mine)

So, i have the sanctum token key and i need to attempt the authentication but sanctum does not provide any method, how can i attempt the login using the token that sanctum use to authenticate?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
