### ISSUE TITLE
personal access token id value not autoincremented 

### ISSUE THREAD

**Issue by uniqueginun** [laravel/sanctum#200]
- Sanctum Version: 2.6
- Laravel Version:7.5.0
- PHP Version: 7.4.7
- Database Driver & Version:

### Description:
when I create new token createToken the generated id value that appended to the plaintext token doesn't match the actual one that been inserted with the record in the database table

### Steps To Reproduce:

when I created new token using this line to generate token and I use it in postman it always gives me 401

$token = $request->user()->createToken($request->name);

in this function $max !== $token->id 

public function createToken(string $name, array $abilities = ['*'])
    {

        $max = PersonalAccessToken::max('id') + 1;

        $token = $this->tokens()->create([
            'name' => $name,
            'token' => hash('sha256', $plainTextToken = Str::random(40)),
            'abilities' => $abilities,
        ]);

        dd($max, $token, $token->id.'|'.$plainTextToken);

        return new NewAccessToken($token, $token->id.'|'.$plainTextToken);
    }

but when I replace the big id that appended to the plaintext token with the real one from the table and use it in postman it works, so why  these two ($max && $token->id ) don't match??

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
