### ISSUE TITLE
Cannot get authenticated user

### ISSUE THREAD

**Issue by ImGelu** [laravel/sanctum#201]
- Sanctum Version: 2.6.0
- Laravel Version: 7.28.3
- PHP Version: 7.4.3

### Description:
Auth::user() and auth()->user() methods don't work in Blade pages

### Steps To Reproduce:
Before using Sanctum, we used the auth()->user() method with JWT. Now, I can't seem to be able to use it in any controller or Blade file (the method returns null).

Is there any other way to get the **currently logged in user**?

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
