### ISSUE TITLE
Allow guests to access API?

### ISSUE THREAD

**Issue by sukhcha-in** [laravel/sanctum#202]
- Sanctum Version: v2.4.2
- Laravel Version: v7.19.1
- PHP Version: 7.4.9

### Description:
I am having routes which use `auth:sanctum` middleware for authenticated users, something like this:
```
Route::group(['middleware' => ['auth:sanctum']], function () {
	Route::get('/user', 'Api\AppController@user');
	//... and so on
});
```
Now I have one route which should be available for both unauthenticated users and authenticated users.<br>
On this route i'm not using `auth:sanctum` to allow access for guest users.<br>
But if any authenticated user comes, I'm not able to execute function for them.<br>
Is there any way to enable optional auth for specific routes?
```
if (Auth::user()) {
	//Unable to access auth status without auth:sanctum route
	//Execute something for authenticated users...
}
```
If I add `auth:sanctum` to this route then guest users are unable to access this API :(<br>

### Steps To Reproduce:
It is just one way to use this route? How to allow guest + authenticated users on same route?

**Comment by driesvints** [comment]
Sanctum isn't really meant to be used for unauthenticated requests.

**Comment by sukhcha-in** [comment]
> Sanctum isn't really meant to be used for unauthenticated requests.

That's okay, but can you understand my situation? I have an API that anyone can access (including guest users), but if any request has authorization token then I want to execute some function for their profile.

**Comment by driesvints** [comment]
I guess in that case you don't need to protect the route with sanctum but just let them provide a user id to retrieve the data for a specific user

**Comment by sukhcha-in** [comment]
> I guess in that case you don't need to protect the route with sanctum but just let them provide a user id to retrieve the data for a specific user

Yeah, I also think that is the only way. Have to remove sanctum from that route.

**Comment by Obacm** [comment]
Do like this.  `Auth::guard('sanctum')->check()`
