### ISSUE TITLE
Trailing '%3D' in XSRF-TOKEN SetCookie Header

### ISSUE THREAD

**Issue by simonbuehler** [laravel/sanctum#205]
- laravel/framework": "^8.0",
- "laravel/sanctum": "^2.6",
- PHP Version: 7.3
- Database Driver & Version: mysql 

### Description:
hi,

when using the http://websockets.test/sanctum/csrf-cookie Endpoint to get the cookie, the response has a additional "=" breaking decryption

response:
```
HTTP/1.1 204 No Content
Date: Tue, 13 Oct 2020 14:24:38 GMT
Server: Apache/2.4.29 (Ubuntu)
X-Powered-By: PHP/7.3.23
Cache-Control: no-cache, private
Set-Cookie: XSRF-TOKEN=eyJpdiI6IlJjMHdPdWdjaHIyQVBKN2VsMDY1aFE9PSIsInZhbHVlIjoiWjdCdUhhLzJXU21YWjlIeXJEMVZNbE83M2xvSDhMd1E3SFBKQ3hBQWhIeS9yWDZ5VHB0ME5aZkJ0S05sNU1kUzc4dFBOTzdYQkNPSFNGUEl1SkpnYW9RUFFKK0Vtd1Z6dXBmZnVMbldXNjhOc0MyTDlKOHMvOUpjK0Q4dlVEc3kiLCJtYWMiOiJmM2JhNmY1OWE1OWU5OWVlYWI1NjE0MzQ1MDJmNzI1NmY5NTJlZmY3NTQwM2RiOWRjNzhiOTIzYTNkNjg0Y2FlIn0%3D; expires=Tue, 13-Oct-2020 16:24:38 GMT; Max-Age=7200; path=/; samesite=lax
Set-Cookie: laravel_session=eyJpdiI6ImFUVjI5ZXF6U0lWVzJRVjRzOUU5NFE9PSIsInZhbHVlIjoidXltS3h6WDladnlqeUI3cWNzcC9VQ2pzdndmSXlsU09WT04vMHRYNnpBcmhLcEFWU0NrL3JzOVdVY21ZVWhnaHZEMnl5Y3NMSUVEMFBkdmp5djYveDhpSzhXS2xScDZsV1ErZDJjR0dqZjhVVjZVYWZ1eEI1UWNkSjExN1I5cTgiLCJtYWMiOiI1N2NhOWM3ZjA1MDI5YjlkNTRhZDViMmQ3NWViNWMyZTkwZjcwMTEzZjY0OWIxZTcxMjk4ODBkYmRlNjA5YWMwIn0%3D; expires=Tue, 13-Oct-2020 16:24:38 GMT; Max-Age=7200; path=/; httponly; samesite=lax
Keep-Alive: timeout=5, max=24
Connection: Keep-Alive
```

any idea how to fix this?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
