### ISSUE TITLE
csrf-cookie resulted in a `504 Gateway Time-out`

### ISSUE THREAD

**Issue by AlifAbhiesa** [laravel/sanctum#206]
- Sanctum Version: 2.1
- Laravel Version: 7.15
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7

### Description:

Limit token of 2500 data on table personal_access_tokens, after that sanctum cant generate csrf token anymore and return the error result "504 Gateway Time-out"

![image](https://user-images.githubusercontent.com/27193997/96071811-1a76a600-0ecd-11eb-8490-2e25ab4bd52d.png)

### Steps To Reproduce:
I'm try deleting a few tokens on table personal_access_tokens, and it's get back to normal.

**Comment by RahulDey12** [comment]
I think your database doesn't have enough power. Try to upgrade your database. And try again

**Comment by AlifAbhiesa** [comment]
> I think your database doesn't have enough power. Try to upgrade your database. And try again

doesn't have enough power like what? my server can handlie more than 200 rps, and the limitation of mysql is 5 billion of rows

**Comment by RahulDey12** [comment]
> > I think your database doesn't have enough power. Try to upgrade your database. And try again
> 
> doesn't have enough power like what? my server can handlie more than 200 rps, and the limitation of mysql is 5 billion of rows

I guessed it

**Comment by driesvints** [comment]
Don't limit it.
