### ISSUE TITLE
Custom fields in PersonalAccessToken

### ISSUE THREAD

**Issue by hopefeda** [laravel/sanctum#208]
I recommend adding the ability to add custom fields to the PersonalAccessToken model. This could be really useful since people have different needs when it comes to login/tokening. For instance, I need to record ip_address_at_creation & last_used_ip_address for the PersonalAccessToken. This potentially means copying the migration file to the migrations folder instead of running it in the background so it can be modified. Alternatively, implement the complicated logic of dynamically adding fields to the migration file according to the config file in the beginning.

Please advise as to how to proceed. If you are not going to add this feature, I would like to create a pull request to add the ip_address_at_creation & last_used_ip_address fields as nullable/optional fields to the PersonalAccessToken model. I think it's fair to say it's better to keep such a widely required option at least optionally available. 

Edit 1:
This obviously also means modifying the models to accept the custom fields.

Regards,

**Comment by driesvints** [comment]
You can already override the models and add any fields to the database table you want: https://laravel.com/docs/8.x/passport#overriding-default-models

**Comment by driesvints** [comment]
Sorry linked to Passport docs there but Sanctum has this as well: https://github.com/laravel/sanctum/blob/2.x/src/Sanctum.php#L62

**Comment by rognales** [comment]
How do I introduce token used counter here? Listen for Model saving event?

**Comment by driesvints** [comment]
@rognales please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
