### ISSUE TITLE
Guest middleware leaking when using api tokens

### ISSUE THREAD

**Issue by hopefeda** [laravel/sanctum#209]
- Sanctum Version: 2.7.0
- Laravel Version: 8.11.2
- PHP Version: 7.4.11
- Database Driver & Version: MySQL 8.0.21

### Description:
The guest middleware leaks(i.e. allows authenticated requests to pass through) when using Api tokens. It works fine for Cookie-based auth though.

### Expected Behaviour
When a valid bearer token is provided, the request is authenticated. Therefore, request must not be able to access routes protected by the "guest" middleware.

### Steps To Reproduce:
1) Authenticate using Api Token (["Mobile App Authentication" in docs](https://laravel.com/docs/8.x/sanctum#mobile-application-authentication))
2) Create a route and assign the "guest" middleware to it.
```
Route::middleware('guest')->get('ping', function() {
    return 'pong';
});
```

**Comment by driesvints** [comment]
The guest middleware doesn't really makes sense from an API point of view. Just don't protect those routes.
