### ISSUE TITLE
Route Prefix with Sanctum as Middleware disables Route::bind

### ISSUE THREAD

**Issue by LeonAlexanderBartz** [laravel/sanctum#211]
- Sanctum Version: 2.7.0
- Laravel Version: 8.11.2
- PHP Version:  7.4.10
- Database Driver & Version:
Non required for bug.
### Description:
When having a rout with a prefix and auth:sanctum as a middleware the Route::bind will not be executed.

### Steps To Reproduce:

Either clone my [example Repo](https://github.com/LeonAlexanderBartz/LaravelRouteAuthBinding)
or follow the steps below.
```bash
laravel new bug-example
cd bug-example
composer require laravel/sanctum
php artisan make:provider BindProvider
```
In the BindProvider:
```php
public function boot()
    {
        // dd();
        Route::bind('binding', function () {
            dd();
        });
    }
```

In the web.php
```php
<?php

use Illuminate\Support\Facades\Route;

Route::prefix('/{binding}')->group(static function () {
    Route::get('/no-auth', function () {
        return view('welcome');
    });

    Route::middleware('auth:sanctum')->group(function () {
        Route::get('/auth', function () {
            return view('welcome');
        });
    });
});

```

Then run:
`php artisan serve`

Now we have two routes:
```
http://127.0.0.1:8000/exapleBind/no-auth
http://127.0.0.1:8000/exapleBind/auth
```

Both should return a blank page.
The no-auth route returns a blank page.
The auth route return a Route [login] not defined. 

When uncommenting the `dd();` in the BindingProvider at the start of the `boot` method both requests will be blank.

**Comment by driesvints** [comment]
The sanctum middleware belongs on api routes, not web routes.

**Comment by driesvints** [comment]
> https://laravel.com/docs/master/sanctum#protecting-routes

**Comment by LeonAlexanderBartz** [comment]
The behavior is the same for api routes. I have pushed the updated api.php to the [demo](https://github.com/LeonAlexanderBartz/LaravelRouteAuthBinding).
api.php:
```php
<?php

use Illuminate\Support\Facades\Route;

Route::prefix('/{binding}')->group(static function () {
    Route::get('/no-auth', function () {
        return view('welcome');
    });

    Route::middleware('auth:sanctum')->group(function () {
        Route::get('/auth', function () {
            return view('welcome');
        });
    });
});

```
Routes:
[http://127.0.0.1:8000/api/123/no-auth](http://127.0.0.1:8000/api/123/no-auth)
[http://127.0.0.1:8000/api/123/auth](http://127.0.0.1:8000/api/123/auth)

**Comment by driesvints** [comment]
Can you try if this works?

```
<?php

use Illuminate\Support\Facades\Route;

Route::prefix('/{binding}')->group(static function () {
    Route::get('/no-auth', function () {
        return view('welcome');
    });

    Route::group(['middleware' => 'auth:sanctum'], function () {
        Route::get('/auth', function () {
            return view('welcome');
        });
    });
});
```

**Comment by LeonAlexanderBartz** [comment]
No it's not working.

**Comment by driesvints** [comment]
I don't have time today to look into this anymore but I'll try to help out soon.

**Comment by LeonAlexanderBartz** [comment]
No problem, i still have other parts of my application that aren't done yet.
Why has this issue the ![](https://img.shields.io/github/labels/laravel/sanctum/needs%20more%20info)  tag ?

**Comment by driesvints** [comment]
Because I still need to verify if this is a bug or not.

**Comment by driesvints** [comment]
I haven't gotten to this yet and with the current PHP 8 updates I probably won't any time soon. Appreciating any help with this issue.

**Comment by dbakan** [comment]
I don't think this is an issue with sanctum. You should get the same results using `auth:web`. 
@LeonAlexanderBartz Can you confirm this?

From what I read, the `SubstituteBindings` middleware will not be triggered, if auth fails.

**Comment by LeonAlexanderBartz** [comment]
> I don't think this is an issue with sanctum. You should get the same results using `auth:web`.
> @LeonAlexanderBartz Can you confirm this?
> 
> From what I read, the `SubstituteBindings` middleware will not be triggered, if auth fails.

Thats right 👍.
Do you have any idea how i can run the Provider before the auth is checked ?
In my case the Provider sets the Database connection where the user is stored.

**Comment by dbakan** [comment]
I submitted a PR to your repo with a suggestion using a custom middleware.

**Comment by LeonAlexanderBartz** [comment]
Tanks everybody for your help. I appreciate it very much.
