### ISSUE TITLE
API Logout Using Default Route Not Working

### ISSUE THREAD

**Issue by phillmorgan28** [laravel/sanctum#212]
- Sanctum Version: 2.7.0
- Laravel Version: 8.11.2
- PHP Version: 7.4
- Database Driver & Version: MySQL 8

### Description:
When calling the default logout route using axios.post, Laravel returns a 204 response indicating a successful logout, however I am still logged in and able to call protected routes.

Using the 3rd party debug bar, I can see that the AJAX request to /logout only runs one query which selects the current user by ID, but doesn't run anything else afterwards which would invalidate the cookie.

This is my auth.js vuex store. The login works fine, but logout doesn't.

```
import axios from 'axios'

axios.defaults.withCredentials = true;

export default {
    namespaced: true,

    state: {
        authenticated: false,
        user: null
    },

    getters: {
        authenticated (state) {
            return state.authenticated
        },

        user (state) {
            return state.user
        },
    },

    mutations: {
        SET_AUTHENTICATED (state, value) {
            state.authenticated = value
        },

        SET_USER (state, value) {
            state.user = value
        }
    },

    actions: {
        async signIn ({ dispatch }, credentials) {
            await axios.get('/sanctum/csrf-cookie')
            await axios.post('/login', credentials)
            return dispatch('me')
        },

        async signOut ({ dispatch }) {
            await axios.post('/logout')
            return dispatch('me')
        },

        me ({ commit }) {
            return axios.get('/api/frontend/user').then((response) => {
                commit('SET_AUTHENTICATED', true)
                commit('SET_USER', response.data)
            }).catch(() => {
                commit('SET_AUTHENTICATED', false)
                commit('SET_USER', null)
            });
        }
    }
}
```

**Comment by phillmorgan28** [comment]
As an update to this, if I write a custom logout function which is protected by the auth:sanctum middleware and call:

`Auth::guard('web')->logout()`

Then the logout is completed successfully.

I think there must be a bug in the default logout function.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
