### ISSUE TITLE
Calling ->user() on request returns tokenable

### ISSUE THREAD

**Issue by marijnbent** [laravel/sanctum#214]
When adding the trait `HasApiTokens` to a different model than `User`, calling `$request->user()` (while authenticated) returns the `tokenable_type` model. Would make more sense to either use the type as function (eg. `$request->source()`) or add `$request->tokenable()`.

Generating a token for a model with the `HasApiTokens` trait:
```
$source = App\Models\Source::find(1);
$source->createToken('test');
```

Using the token in an authenticated request:
```
$request->user();
=> App\Models\Source {#2129
     id: 1,
     created_at: "2020-10-27 20:54:18",
     updated_at: "2020-10-27 20:54:18",
   }
```

**Comment by driesvints** [comment]
Feel free to propose a pr if you like
