### ISSUE TITLE
fromFrontend() is unreliable when testing API Controllers from Postman

### ISSUE THREAD

**Issue by meglio** [laravel/sanctum#218]
- Sanctum Version: 2.8.0
- Laravel Version: 8.13.0
- PHP Version: 7.4
- Database Driver & Version: PostgreSQL 13

### Description:

`fromFrontend()` is unreliable when testing API Controllers from Postman.

### Steps To Reproduce:

1. Integrate Sanctum the "official" way as documented in the guides.
2. Create an API controller
3. Call the API controller from Postman. 

When testing from Postman or similar tools, `referer` and `origin` headers might be missing. This is normal. Adding the referrers to Postman does work but it is a workaround. Instead, you should fix the code.

The code should assume that both `referer` and `origin` can be absent. In this case, the `$domain` variable is set to `null`:

`$domain = $request->headers->get('referer') ?: $request->headers->get('origin');`

if this is the case, the code that follows is conceptually wrong:

```
$domain = Str::replaceFirst('https://', '', $domain);
        $domain = Str::replaceFirst('http://', '', $domain);
        $domain = Str::endsWith($domain, '/') ? $domain : "{$domain}/";

        $stateful = array_filter(config('sanctum.stateful', []));
```

it leads to the domain name = `/` which makes no sense, since the domain name I access the controller through is `test.lvh.me`.

**Comment by driesvints** [comment]
You always need to add an origin or referer header.
