### ISSUE TITLE
Invalid old sanctum token

### ISSUE THREAD

**Issue by irvv17** [laravel/sanctum#220]
- Available token:

### Description:

IDK the reason for this, but I think it would be better than Old tokens get invalid when you request another new one.

### Steps To Reproduce:

1. Get a new token with `createToken('example-token');` method

2.  Get **new token** with `createToken('example-token');` method (in the same URL), EXAMPLE: `{{host}}/{{apibasev1}}/auth/login`

3. REQUEST something in your API LIKE `{{host}}/{{apibasev1}}/user/1` which is protected by sanctum middleware and OOPS (at least in this "ISSUE CASE") the URL will respond every **TOKEN** generated

It is just an Idea.

what do you think?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
