### ISSUE TITLE
Get session token for user 

### ISSUE THREAD

**Issue by sunkakar** [laravel/sanctum#221]
I currently have a project which is based in PHP and only uses Laravel Jetstream to add authentication to a specific route. 

The Laravel Application lives at: domain.com/auth
The files that need to have an Auth layer are at: domain.com/members

I need to embed a php code snippet in the files in 'domain.com/members' such that `if not authenticated, redirect to login`. 

I have not been able to achieve this as I'm having trouble getting the token even after I authenticate the user.

This is my ApiController for an route named 'api' I created
```
class ApiController extends Controller
{
    public function check(Request $request){
        if($request->user()->email)
        {
            $authJSON = json_encode($auth_array); 

            $request->session()->put('logged_in',true);

            return json_encode($request->session()->all());
        }
        return $request->user();
    }
}
```

This is the code snippet in question that runs into the login page each time I try to access it: 
```
<?php
    ini_set("allow_url_fopen", 1);
    $json = file_get_contents('domain.com/auth/api/check');
    $obj = json_decode($json);

    if(is_object($obj))
    {
        echo "HERE:  ";
        echo $obj->logged_in;
    }
    else
    {
        //echo("<script>location.href = 'https://".$_SERVER['HTTP_HOST']."/auth';</script>");
    }

?>
```

Any opinions, ideas, help? I would really appreciate it

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
