### ISSUE TITLE
Unable to run auth()->loginUsingId() in Controller but in Livewire it is fine.

### ISSUE THREAD

**Issue by rezuankassim** [laravel/sanctum#222]
- Livewire Version: v2.3.1
- Sanctum Version: v2.7.0
- Laravel Version: v8.12.3
- PHP Version: 7.4.10
- Database Driver & Version: Mysql, 5.7.31

### Description:

I have a impersonating function in my Livewire components using the code `auth()->loginUsingId($user_id)`.

This works and I have successfully switch to the user, but when I wanted to switch back to the original user using my controller using the code `auth()->loginUsingId($user_id)`, it will prompt out the error below.
```
Method Illuminate\Auth\RequestGuard::loginUsingId does not exist.
```

This is output I got when trying to debug.
``` php
// In Livewire component
public function mount() {
    dd(auth()->check()); // true
    dd(auth('sanctum')->check()); // true
    dd(auth('web')->check()); // true
    dd(auth()->getDefaultDriver()); // sanctum
}
...
public function switch() {
    dd(auth()->check()); // true
    dd(auth('sanctum')->check()); // true
    dd(auth('web')->check()); // true
    dd(auth()->getDefaultDriver()); // web
}
```

``` php
// In controller
public function store()
{
    dd(auth()->check()); // true
    dd(auth('sanctum')->check()); // true
    dd(auth('web')->check()); // true
    dd(auth()->getDefaultDriver()); // sanctum
}
```

### Steps To Reproduce:
1. Create new Laravel project with Jetstream and Livewire stack
2. Use `auth()->loginUsingId()` in a Livewire component
3. Use `auth()->loginUsingId()` in a controller

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by siarheipashkevich** [comment]
@rezuankassim did you find the solution how to use loginUsingId with Sanctum?
