### ISSUE TITLE
Database Driver doesn't work on subdomain routing

### ISSUE THREAD

**Issue by safjammed** [laravel/sanctum#223]
- Sanctum Version: 2.8.0
- Laravel Version: 8.14.0
- PHP Version: 7.4
- Database Driver & Version:MYSQL 5.7.32-0ubuntu0.18.04.1

### Description:
I have cross domain routing enabled. all my requests are handled my api.{SITE_URL} and i serve my apps from console.{SITE_URL} and {SITE_URL}. 
I am getting the following error ever since i've swithced my session driver from redis to database
```
CSRF token mismatch
```
I need to have database as my session driver. When i have redis as my database driver it works fine. Please help, I have scoured the internet, no answer available.

### Steps To Reproduce:
This is my config/cors.php
```
'paths' => ['*'],

    'allowed_methods' => ['*'],

    'allowed_origins' => ['*'],

    'allowed_origins_patterns' => [],

    'allowed_headers' => ['*'],

    'exposed_headers' => [],

    'max_age' => 0,

    'supports_credentials' => true,
```

http/kernel.php
```
 protected $middleware = [
        // \App\Http\Middleware\TrustHosts::class,
        \App\Http\Middleware\TrustProxies::class,
        \Fruitcake\Cors\HandleCors::class,
        \App\Http\Middleware\PreventRequestsDuringMaintenance::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,

        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,


    ];

    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            EnsureFrontendRequestsAreStateful::class,
            'throttle:60,1',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

.env file

```
SESSION_DOMAIN=".domain.local"
SANCTUM_STATEFUL_DOMAINS="console.domain.local,domain.local,localhost,127.0.0.1"
APP_URL=http://domain.local
APP_BASE_URL=domain.local
```

**Comment by driesvints** [comment]
Hey there,

> Please help, I have scoured the internet, no answer available.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
