### ISSUE TITLE
Updating "last_updated_at" field with sqlServ gives back error

### ISSUE THREAD

**Issue by NoxxieNl** [laravel/sanctum#224]
- Sanctum Version: 2.8.0
- Laravel Version: 8.11.2
- PHP Version: 7.4.7
- Database Driver & Version: SqlServer & 7.4

### Description:
When the "last_updated_at" field is updated inside the table (Guard.php line 73) the default datetime. With SqlServer this throws the error "The conversion of a nvarchar data type to a datetime data type resulted in an out-of-range value."

### Steps To Reproduce:
Connect to an sqlserv and force update the "last_updated_at" field in the "personal_access_token" table.

### Work around
Currently the only work around I found was overwrite the default "PersonalAccessToken.php" as stated in the documents and add the _GetDateFormat()_ method in order to fix it.

Would be nice if you could set the DTS from the config so if you are using the default PersonalAccessToken.php file you can still overwrite the DTS storage.

Is this something a PR could be created for in order to add this functionality, or am I missing a feature in Laravel to already do this? :)

**Comment by driesvints** [comment]
There is no `last_updated_at` in the `personal_access_token` table.

https://github.com/laravel/sanctum/blob/2.x/database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
