### ISSUE TITLE
Can I use "Authenticate A User By ID" with Sanctum?

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/sanctum#231]
- Sanctum Version: 2.8.1
- Laravel Version: 8.15.0
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 8.0.22

### Description:

Hi all.

Could you please suggest how I can use [Authenticate A User By ID](https://laravel.com/docs/8.x/authentication#authenticate-a-user-by-id) with Sanctum?

I need impersonate user by another user.

### Steps To Reproduce:

`Auth::loginUsingId($impersonateUser);`

The error which I'm getting:
Method Illuminate\Auth\RequestGuard::loginUsingId does not exist.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ndmgrphc** [comment]
There's still no solution to this despite being asked on other channels.  It's asked on every channel and still unanswered.  Thus, why are these methods not implemented?  Are the maintainers open to implementing them?

**Comment by andreladocruz** [comment]
@driesvints we use the https://github.com/404labfr/laravel-impersonate package, but it does not seams to work with sanctum.

Any help in how can we get the same result when working in a SPA environment???

**Comment by phalouvas** [comment]
same problem here

**Comment by tntsoft** [comment]
Why is this closed without being addressed?

**Comment by elephantux** [comment]
same problem here
