### ISSUE TITLE
Sanctum Default Guard is Web? 

### ISSUE THREAD

**Issue by JeffreyHosler** [laravel/sanctum#232]
- Laravel Version: 8.17.0
- PHP Version: 7.4.2
- Database Driver & Version: MySql 5.7.26

### Description:
So I have a unique situation where the site we have is a basic Laravel app. The Admin Panel is a spa, and the Webinars Platform is an SPA. They both use Sanctum.

The Admin panel uses the Users Table. And the Webinars Platform uses the Attendants Table. Basically users can authenticate to get into the admin panel, but Attendants can authenticate to get into a webinar. I have a problem where Attendants return with a 401 error, but not the User. 

I did some digging and I believe the issue is here in Gaurd.php
```php
 public function __invoke(Request $request)
    {
        if ($user = $this->auth->guard(config('sanctum.guard', 'web'))->user()) {
            return $this->supportsTokens($user)
                        ? $user->withAccessToken(new TransientToken)
                        : $user;
        }
```

Where it sets the default Guard to web if no config is set, and Web defaults to the users table. I can't add this config because then the Admin panel won't work for Users. Any way for this to be dynamic in some way?

**Comment by JeffreyHosler** [comment]
Right now I got around this by adding this to my webinar api routes

```
	config(['sanctum.guard' => 'web_attendant']);
```

and adding this to my admin api routes
```
	config(['sanctum.guard' => 'web']);
```

Here are my guards
```
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
		],
		
		'web_attendant' => [
            'driver' => 'session',
            'provider' => 'attendants',
		],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],

        'sanctum' => [
            'driver' => 'sanctum',
            'provider' => 'users',
		],

		'sanctum_attendant' => [
            'driver' => 'sanctum',
            'provider' => 'attendants',
        ],
    ],
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by RahulDey12** [comment]
@JeffreyHosler I was facing the same issue many days ago. So check the configuration on this PR #149
