### ISSUE TITLE
Logout with authentication with SPA and Mobile (bearer token) 

### ISSUE THREAD

**Issue by Sporium** [laravel/sanctum#234]
- Sanctum Version: 2.8.2
- Laravel Version: 8.19.0
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:
Can't delete token via user()->currentAccessToken()->delete() when use both SPA (CSRF) and mobile (bearer token) authentication.

### Steps To Reproduce:
If you login with and logout  like this
` public function login(Request $request)
    {
        $user = User::firstWhere('email', $request->email);
        if (!$user || !auth()->attempt($credentials)) {
            throw ValidationException::withMessages([
                'error' => ['The provided credentials are incorrect.'],
            ]);
        }
        return $user->createToken($request->userAgent());
    }
 public function logout(Request $request)
    {
  $request->user()->currentAccessToken()->delete();
        return response()->json(null);
    }
`
and have EnsureFrontendRequestsAreStateful::class, in Kernel.
You will get error

> message: "Call to undefined method Laravel\Sanctum\TransientToken::delete()"

but if you use  this
`if (!$user || !Hash::check($credentials)) {
            throw ValidationException::withMessages([
                'email' => ['The provided credentials are incorrect.'],
            ]);
        }`
Logout successful.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
