### ISSUE TITLE
has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Aisakk** [laravel/sanctum#237]
- Sanctum Version: ^2.8
- Laravel Version: ^8.12"
- PHP Version: "^7.3|^8.0",
- Database Driver & Version:

### Description:
![Alt Text](https://dev-to-uploads.s3.amazonaws.com/i/7alk3xds8fl4v34wig0k.jpg)

Hello, i have this error, I dont know if my configuration is bad, or is correctly. 
File config\cors.php

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Cross-Origin Resource Sharing (CORS) Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may configure your settings for cross-origin resource sharing
    | or "CORS". This determines what cross-origin operations may execute
    | in web browsers. You are free to adjust these settings as needed.
    |
    | To learn more: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
    |
    */

    'paths' => [
        'api/*', 
        '/*',
        'register',
        'sanctum/csrf-cookie', 

    ],

    'allowed_methods' => ['*'],

    'allowed_origins' => ['*'],

    'allowed_origins_patterns' => [''],

    'allowed_headers' => ['*'],

    'exposed_headers' => [],

    'max_age' => 0,

    'supports_credentials' => true,

];

```
config\sanctum.php
```
  'stateful' => explode(',', env(
        'SANCTUM_STATEFUL_DOMAINS',
        'localhost, 127.0.0.1'
       // 'localhost,localhost:8080,127.0.0.1,127.0.0.1:8080,::1'
    )),
```
Kernel.php
```
  protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            EnsureFrontendRequestsAreStateful::class,
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

Model user.php I add HasApitokens and my file .env i have:
```
SESSION_DOMAIN=localhost:8080 
SANCTUM_STATEFUL_DOMAINS=localhost:8080
```
I use too only localhost, in my project file main of vuejs i have this:

```
Vue.config.productionTip = false
Vue.prototype.$http = axios
axios.defaults.withCredentials = true
axios.defaults.baseURL = 'http://localhost:8000/'

Vue.use(VueCountryCode);

new Vue({
  router,
  vuetify,
  store,
  render: h => h(App)
}).$mount('#app')
```
and in the methods to send the form i have this
```
 sendRegister(){
         this.$http.get('sanctum/csrf-cookie').then(() => {
           this.$http.post('register', this.form).then(res=>{
              console.log(res)
           })
        });
      },
```
And i have the error that show you in the images, what is my error in this configuration :/ 
![screen](https://user-images.githubusercontent.com/43797095/103144586-90d02980-4702-11eb-9383-a6017b91bf7a.jpg)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
