### ISSUE TITLE
Artisan migrate is executing migration file in vendor

### ISSUE THREAD

**Issue by LeftPinkie** [laravel/sanctum#242]
- Sanctum Version: 2.8.2
- Laravel Version: 8.21.0
- PHP Version: 7.4.6
- Database Driver & Version: MySQL v8.0.20

### Description:
When I run `php artisan migrate`, artisan is picking up the migration file from the vendor directory (`./vendor/laravel/sanctum/database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php`).

### Steps To Reproduce:
1. disable the migration file in my app (`./database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php`)
2. run `php artisan migrate`:
   ```
   ...
   Migrating: 2019_12_14_000001_create_personal_access_tokens_table
   Migrated:  2019_12_14_000001_create_personal_access_tokens_table (32.20ms)
   ```

When I disable (rename) the migration file `./vendor/laravel/sanctum/database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php`, artisan does not pick it up.

**Comment by driesvints** [comment]
That's intended. I'm guessing you didn't put `Sanctum::ignoreMigrations` in your service provider. See https://laravel.com/docs/8.x/sanctum#migration-customization
