### ISSUE TITLE
Possibility of having an AccessToken.php Interface

### ISSUE THREAD

**Issue by AndreKendeck** [laravel/sanctum#244]
- An ex-colleague had to implement basic Api Authentication on an existing Laravel application using [MongoDB](https://github.com/jenssegers/laravel-mongodb) instead of MySQL/MariaDB. Since the `PersonalAccessToken.php` Model directly inherits `Illuminate\Database\Eloquent\Model` using `Jenssegers\Mongodb\Eloquent\Model` is not possible because the `NewAccessToken.php` expects an Eloquent Model. 

**Proposed Approach**

- Have a `Laravel\Sanctum\Contracts\AccessToken` Interface 
- Have the existing `PersonalAccessToken.php` class implement that interface
- Have the `NewAcessToken.php` accept the `AccessToken.php` interface instead of the `PersonalAcessToken.php` Model.

``` php
namespace Laravel\Sanctum\Contracts;

interface AccessToken
{
}
```

```php
class NewAccessToken implements Arrayable, Jsonable
{
    /**
     * Create a new access token result.
     *
     * @param  \Laravel\Sanctum\Contracts\AccessToken  $accessToken
     * @param  string  $plainTextToken
     * @return void
     */
    public function __construct(AccessToken $accessToken, string $plainTextToken)
    {
        $this->accessToken = $accessToken;
        $this->plainTextToken = $plainTextToken;
    }
}
```

```php
class PersonalAccessToken extends Model implements HasAbilities, AccessToken
{
} 
```

**Comment by taylorotwell** [comment]
This is one of those things that is just easier to discuss in a proposed PR. I do worry about boxing myself into always having to be Eloquent agnostic with Sanctum. It is convenient for me to be able to rely on Eloquent when implementing features, etc.

**Comment by AndreKendeck** [comment]
😅 I agree with the convenience of Eloquent, again this is a **very** specific use-case. It's very rare for developers to reach for MongoDB when using Laravel.

 I also don't think its worth the trouble abstracting this functionality to an interface to accommodate for such a use case. 

Thanks for the feedback. 😁
