### ISSUE TITLE
Sanctum not working with shared Hosting and Mobile App

### ISSUE THREAD

**Issue by fathialamre** [laravel/sanctum#248]
Sanctum not working with a shared hosting (CPanel)
I'm use this seteps but  not working

1. New laravel app with a sub domain on valet - composer install sanctum.
2. Add the SANCTUM_STATEFUL_DOMAIN in the env with the parent domain e.g video.mysite.test
3. Add SESSION_DOMAIN to env .mysite.test
4. Add the additional kernel code based on the docs
5. Add sanctum middleware to api.php 👍 
6. Route::group(['middleware' => 'auth:sanctum'], function () {
7. Try and do a api call with axios, you will get 401 Unauthorized

Thanks

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by fathialamre** [comment]
Thanks
