### ISSUE TITLE
Sanctum throws "Session store not set on request"

### ISSUE THREAD

**Issue by Sell24** [laravel/sanctum#249]
- Sanctum Version: 2.9.0
- Laravel Version: 8.26.1
- PHP Version: 7.3.26
- Database Driver & Version: MYSQL v5.7.33

Description:
Posted on Laracasts: [https://laracasts.com/discuss/channels/laravel/sanctum-throws-session-store-not-set-on-request](https://laracasts.com/discuss/channels/laravel/sanctum-throws-session-store-not-set-on-request)
(note: my post is under khalilm)

When using a SPA with manual login, Sanctum will throw an "Session store not set on request" during login.  This does not occur on local hardware. There is a "fix" posted there but this has now been challenged as incorrect.

Steps To Reproduce:
1. Set up Laravel Sanctum following the documentation. Login will work locally. However when moving to a production machine with the same setup, the log in fails. I know this is not fully detailed steps, however, I am not sure what specifically to post as there is a lot of configuration, which I will do if requested. No offense but in all the issues I looked at here, you asked them to post elsewhere after they had already inputted a detailed explanation.

I want to note that after the suggested change, the code seems to work. CSRF tokens are received and sanctum middleware works. I am looking for your input on whether you agree with the fix or whether there is something else that should be done instead.

Thanks.

**Comment by driesvints** [comment]
The fact that it works locally and not on production hints at a configuration issue either server side, environment variables or something else. This is something that's best asked on a support channel as this probably isn't a bug in Sanctum and we don't provide debugging support on our issue trackers, sorry.

Try reposting on the Laracasts forums or another one of these channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by Sell24** [comment]
I would like to reopen this issue as I have found the cause of the issue.

If my url has a www. in it, fromFrontend in EnsureFrontendRequestsAreStateful.php will fail. 

So, https://xxx.yyy.com will work. https://www.xxx.yyy.com will not

Adding this line, $domain = Str::replaceFirst('www.', '', $domain);  will fix it (as I am sure you know)

**Comment by driesvints** [comment]
I'll re-open this and have a look tomorrow. Thanks

**Comment by driesvints** [comment]
I didn't get to this sorry. I still think it's nothing to do with Sanctum but with a config issues. Can you try one of the support channels until I get to this?

**Comment by Sell24** [comment]
No issues, people get busy. 

As I mentioned, I fixed it by looking for a www. in the URL. 

I am trying to understand though how you consider this a config issue. Are you saying I need to add www. to the SANCTUM_STATEFUL_DOMAINS in the .env file rather than having the code look for this?

Right now in vendor\laravel\sanctum\src\Http\Middleware\EnsureFrontendRequestsAreStateful.php, the function fromFrontend will filter out http:// and https://  but does not consider if the URL contains a "www."

<code>

public static function fromFrontend($request)

    {
        $domain = $request->headers->get('referer') ?: $request->headers->get('origin');

        $domain = Str::replaceFirst('https://', '', $domain);
        $domain = Str::replaceFirst('http://', '', $domain);
        $domain = Str::replaceFirst('www.', '', $domain); //ADDED THIS LINE
        $domain = Str::endsWith($domain, '/') ? $domain : "{$domain}/";

        $stateful = array_filter(config('sanctum.stateful', []));

        return Str::is(Collection::make($stateful)->map(function ($uri) {
            return trim($uri).'/*';
        })->all(), $domain);
    }
</code>

So, https://subdomain.domain.com and https://domain.com will work.

 But any URL with "www." will not, so
https://www. subdomain.domain.com or https://www.domain.com both will fail to be seen coming from the same domain.

That is why I am suggesting also looking for the www. as shown in the code

**Comment by driesvints** [comment]
I'm sorry but it works for me locally. The best thing you can do now is to create a repo which reproduces the problem. Please commit any custom changes separately from the base Laravel skeleton.

**Comment by Sell24** [comment]
That is the thing with this issue, it will work locally but will not in production. 

I have seen that more people have commented that they are having the same issue on Laracast (https://laracasts.com/discuss/channels/laravel/sanctum-throws-session-store-not-set-on-request).

The thing is that I am using Laravel as an API service and as I mentioned it only happens on production servers, so I will have figure out a way to reproduce this for you. If you have any ideas please let me know.

**Comment by driesvints** [comment]
Feel free to open up a new issue when you've found a clear way to reproduce this. Thanks
