### ISSUE TITLE
Suggestion: Add an optional expires_at to tokens

### ISSUE THREAD

**Issue by Zoefschildpad** [laravel/sanctum#250]
It would be nice to be able to specify when a token is set to expire on a per-token basis, rather than just globally.

For example GitLab lets you set "expires at" when creating tokens. So you can create a token used for importing data that expires in a month, but the token used to deploy your application to never expire.

Or perhaps you want tokens in your application with specific abilities to expire more quickly than those with other abilities.

I think that would add a lot of flexibility to tokens.

**Comment by driesvints** [comment]
If you can PR something so we can look at actual code and what it would take to implement this that'd be great 👍
