### ISSUE TITLE
PersonalAccessToken::$casts type must be array

### ISSUE THREAD

**Issue by profd2004** [laravel/sanctum#251]
- Sanctum Version: v2.9.0
- Laravel Version: v8.28.1
- PHP Version: 8.0.2
- Database Driver & Version: postgres@13.2

### Description:
PHP Fatal error: Type must be 'array' (as in base class \Illuminate\Database\Eloquent\Concerns\HasAttributes)

### Steps To Reproduce:
Great Question, IDEs whine about and referencing PersonalAccessToken anywhere  causes a fatal error.

**Comment by driesvints** [comment]
Someone in Telescope had the exact same issue but couldn't reproduce it in a fresh app. Most likely this is related to something specific to your code. If you can reproduce this in a fresh Laravel app with the minimum amount of code needed then we can help you out. Please commit your changes separately from the base skeleton.

https://github.com/laravel/telescope/issues/1017
