### ISSUE TITLE
Sanctum: Issue with user logout case + TDD

### ISSUE THREAD

**Issue by Cintrust** [laravel/sanctum#256]
- Sanctum Version:^2.9
- Laravel Version: ^8.12
- PHP Version:7.3.9
- Database Driver & Version: Mysql

### Description:
I am writing a use case to logout a user, so on  Logout request, I delete the user tokens so that token issued previously becomes invalid for further requests, but on the second request, the user is still logged in.

I have searched online, many other instances of such issues exist with no solution
https://laracasts.com/discuss/channels/testing/tdd-with-sanctum-issue-with-user-logout-case

### Steps To Reproduce:
1. Create Laravel app with Sanctum.
2. Create Two Endpoint : Login and Logout (Protect Logout with auth:sanctum)
3. Create test Case: send a request to login.
4. Send two request to logout route.
observed behaviour: Both requests will succeed
Expected Behavior: only the first request should succeed, the second request should fail.

My code:
```
//  route/api.php
Route::post('/login',[AuthenticateController::class,"login"])->name("login");

Route::post('/logout',[AuthenticateController::class,"destroy"])->middleware("auth:sanctum")->name("logout");
```

```
// login method
  public function login(Request  $request): array
    {
        $request->validate([
            'email' => 'required|email',
            'password' => 'required',
//        'device_name' => 'required',
        ]);

        /** @var User $user */
        $user = User::where('email', $request->email)->first();

        if (!$user || !Hash::check($request->password, $user->password)) {
            throw ValidationException::withMessages([
                'email' => ['The provided credentials are incorrect.'],
            ]);
        }

        return ["token" => $user->createToken($request->email)->plainTextToken];
    }
```
```
//logout
  public function destroy(Request $request)
    {

        // Revoke the token that was used to authenticate the current request...
        /** @var User $user */
        $user = $request->user();
        /** @var \Laravel\Sanctum\PersonalAccessToken $accessToken */
        $accessToken = $user->currentAccessToken();
  
        $accessToken->delete();


        return response( null,204);

    }
```

```
 public function test_logout()
    {
        /** @var User $user */
        $user = User::factory()->create();

        $response = $this->post(route("login"),
            ["email"=>$user->email,"password"=>"password"]
        );

        $response->assertStatus(200)->assertJson([
            'token' => true,
        ]);

        $token = $response->json("token");
        $this->withHeader("Authorization","Bearer $token");

        $testResponse = $this->post(route("logout"));
        $testResponse->assertNoContent();

     
      $testResponse = $this->post(route("logout"));
        $testResponse->assertNoContent();  //this is supposed to fail.

    }

```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Cintrust** [comment]
@driesvints
Someone has already identified it as an issue on laracast. I posted the link in my post. 

https://laracasts.com/discuss/channels/testing/tdd-with-sanctum-issue-with-user-logout-case


More of such exist on laracast. 
I can provide you with more links

**Comment by driesvints** [comment]
Can you provide a repo that reproduces the issue with the minimum amount of code needed? Please commit any custom changes separately from the base skeleton.

**Comment by Cintrust** [comment]
@driesvints 
while I create a repo for that, can you go through this link
https://laracasts.com/discuss/channels/laravel/tokenguard-api-retrieving-old-user-after-second-request
Someone had a similar issue. He pointed out the fact that the issue might be because TokenGuard is never re-built between multiple requests in a given test.

**Comment by Cintrust** [comment]
@driesvints 
repo: https://github.com/Cintrust/sanctum

**Comment by Cintrust** [comment]
hello, any update yet?

**Comment by driesvints** [comment]
I didn't found time yet to check into this again

**Comment by Cintrust** [comment]
Alright, waiting for your update

**Comment by driesvints** [comment]
@Cintrust I just saw your repo. Can you please commit your custom changes separately from the base skeleton like I asked? Otherwise it's gonna be hard for me to see what you've changed.

**Comment by Cintrust** [comment]
I only changed `routes/api.php` and added `tests/Feature/AuthTest.php`

can you be able to work with that info or should delete the whole repo and do it again?

**Comment by driesvints** [comment]
Yeah please create a new repo, thanks. I need to know about all custom changes.

**Comment by Cintrust** [comment]
https://github.com/Cintrust/sanctum_new

that's the new repo

**Comment by driesvints** [comment]
@Cintrust you're performing multiple HTTP calls in a single test. This isn't supported. Honestly I think there's simple something wrong with your specific setup. As this isn't a support channel I'm going have to ask you to try some of the channels from above again. Sorry.

**Comment by Cintrust** [comment]
yea, I forgot to add `HasApiTokens` trait in my User model before pushing the repo. I have fixed that and pushed to the repo.

`you're performing multiple HTTP calls in a single test. This isn't supported.`
Wow. So can it be supported?

**Comment by xyfantis** [comment]
@Cintrust i have a similar issue and after @driesvints comment on multiple HTTP calls are not supported in a single test i tried and added `$this->refreshApplication();` between the calls in order to mimic distinct HTTP calls. Give it a try it might work for you as well.

**Comment by ProgrammerZ** [comment]
`$this->refreshApplication()` as suggested by @xyfantis works well, but if you are using `RefreshDatabase` and need to persist data between multiple requests that would not work.
I used `Auth::guard('sanctum')->forgetUser()` instead.
