### ISSUE TITLE
Cannot Overriding Default Model

### ISSUE THREAD

**Issue by tyronehey** [laravel/sanctum#259]
- Sanctum Version: 2.9.1
- Laravel Version: 8.32.1
- PHP Version: 8.0.3
- Database Driver & Version: MongoDB & 3.8.3

### Description and Steps To Reproduce:
In docs, the overriding default model is easy as extending the default model. 
I want to use sanctum with MongoDB, so I can't simply extend the default model because it depends on the eloquent model. So I should write a new ```PersonalAccessToken``` similar class with extending the MongoDB model. But, it throws TypeError exception with this message:
```
Laravel\\Sanctum\\NewAccessToken::__construct(): Argument #1 ($accessToken) must be of type Laravel\\Sanctum\\PersonalAccessToken, App\\Models\\Sanctum\\PersonalAccessToken given, called in /var/www/vendor/laravel/sanctum/src/HasApiTokens.php on line 52
```
This error occurs because ```NewAccessToken``` depends on the default ```PersonalAccessToken``` model. the ugly way to solve this problem is aliasing ```Laravel\\Sanctum\\PersonalAccessToken``` to my class but
Sanctum already provides a way to overriding the default model. The only change we need is defining an interface, so now ```NewAccessToken``` will depend on the interface instead of the default model, then the default model implements the interface.

I know MongoDB doesn't support it officially in Laravel, and Sanctum will not support it. but as I already told above, Sanctum can already be customizable with an overriding default model, and with that changes, it will let us use it with unofficial database drivers.

If this change is okay with you, I'm ready to contribute and make a pull request.

**Comment by driesvints** [comment]
We only support extending the default model and are probably not going to consider adding an interface, sorry.

**Comment by mattg66** [comment]
@tyronehey how did you fix this please? Devs please consider adding support for this.

**Comment by smartssa** [comment]
Trying to migrate tymon/jwt to sanctum support and push my app to Laravel 9 but I can't override the default model using Mong. Sounds like the solution is an easy interface. Would love this.

**Comment by smartssa** [comment]
> @smartssa have you managed to migrate anything over? Would love to know how you approached the problem of having a password hash in the database of a user that was created using the JWT secret and the customer's password, how do we match them to migrate over to this?

Sorry, I don't think our original usage was the same. My users hare bcrypt hashes, which all still work.

**Comment by sts-ryan-holton** [comment]
@smartssa any suggestions on how I could migrate?

**Comment by NathanVss** [comment]
I was facing the same issue using MongoDB.

What I did is aliasing the class, as you mentioned @tyronehey

In one of my providers I used:



```
    public function boot()
    {
        $this->registerPolicies();
        
        class_alias(PersonalAccessToken::class, \Laravel\Sanctum\PersonalAccessToken::class);
        Sanctum::usePersonalAccessTokenModel(PersonalAccessToken::class);
    }

```

And it seems to work well, at least for now :) 

Why not adding an interface @driesvints ?

**Comment by AntonyMN** [comment]
> I was facing the same issue using MongoDB.
> 
> What I did is aliasing the class, as you mentioned @tyronehey
> 
> In one of my providers I used:
> 
> ```
>     public function boot()
>     {
>         $this->registerPolicies();
>         
>         class_alias(PersonalAccessToken::class, \Laravel\Sanctum\PersonalAccessToken::class);
>         Sanctum::usePersonalAccessTokenModel(PersonalAccessToken::class);
>     }
> ```
> 
> And it seems to work well, at least for now :)
> 
> Why not adding an interface @driesvints ?

This specifically works in the `AuthServiceProvider` class.

**Comment by RahulDey12** [comment]
If your model extends sanctum's `PersonalAccessToken` the issue won't occur in the first place. But I am not sure if it can be supported by mongo.
