### ISSUE TITLE
Typing variables in a class php 7.4

### ISSUE THREAD

**Issue by i-prikot** [laravel/sanctum#260]
- Sanctum Version: 2.4
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7.29

### Description:
Type of Laravel\\Sanctum\\PersonalAccessToken::$casts must be array (as in class Illuminate\\Database\\Eloquent\\Model)

**Comment by driesvints** [comment]
These can't be applied because the parent doesn't have them. It's unlikely we'll ever introduce these.

**Comment by i-prikot** [comment]
@driesvints If you install php version 7.4 in composer laravel will update the parent model. And this model will contain typing variables.

**Comment by driesvints** [comment]
I don't see that. Can you point out where you see that?
