### ISSUE TITLE
Changed Primary Key will not be used in created token's plainTextToken

### ISSUE THREAD

**Issue by tpetry** [laravel/sanctum#261]
- Sanctum Version: 2.9.1
- Laravel Version: 8.32.1
- PHP Version: 8.0.3
- Database Driver & Version: PostgreSQL 13

### Description:
In the description of Sanctum it is described how migrations and also the model can be customized, which is really excellent. However, in the `createToken` method of the `HasApiTokens` trait the name of the primary key is hardcoded so that a change of the primary key is not applied, the generic `getKey()` method of Eloquent models should be used instead.

https://github.com/laravel/sanctum/blob/d1e2354d94adad9685cf59b2ab0727b8d8f0a19c/src/HasApiTokens.php#L52

**Comment by driesvints** [comment]
Thanks for the pr 👍
