### ISSUE TITLE
Cannot declare class when using replacement PersonalAccessToken model

### ISSUE THREAD

**Issue by mattg66** [laravel/sanctum#263]
- Sanctum Version: 2.9.2
- Laravel Version: 8.33.1
- PHP Version: 8.0.2
- Database Driver & Version: MongoDB

### Description:
Attempting to define a new model which uses MongoDB instead of Eloquent. 
I have created a new PersonalAccessToken model in app/Models/Sanctum/ with the content described in the docs:
`use Laravel\Sanctum\PersonalAccessToken as SanctumPersonalAccessToken;
class PersonalAccessToken extends SanctumPersonalAccessToken
{
    // ...
}`

Within the AuthServiceProvider, I have then added the following line within the boot function:

`        Sanctum::usePersonalAccessTokenModel(PersonalAccessToken::class);
`

I made sure to add `use App\Models\Sanctum\PersonalAccessToken;` so the custom model can be used.

When making a request to issue a new Sanctum token, I get the following error in the logs:

`[2021-03-24 14:25:52] local.ERROR: Cannot declare class PersonalAccessToken, because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot declare class PersonalAccessToken, because the name is already in use at \\app\\Models\\Sanctum\\PersonalAccessToken.php:4)
`

**Comment by driesvints** [comment]
Please see https://github.com/laravel/sanctum/issues/259

**Comment by mattg66** [comment]
To anyone who stumbles on this, to fix this do the following:

1. Copy the /vendor/laravel/sanctum/src/PersonalAccessToken.php file to /app/overrides/PersonalAccessToken.php
2. Edit the /app/overrides/PersonalAccessToken.php and replace `use Illuminate\Database\Eloquent\Model;` with `use Jenssegers\Mongodb\Eloquent\Model;`
3. Edit your composer.json file and edit the autoload section to look like the following:
`"autoload": {
        "exclude-from-classmap": ["vendor\\laravel\\sanctum\\src\\PersonalAccessToken.php"],
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/",
            "Laravel\\Sanctum\\": "app/overrides/"
        }
    },`
This might differ between OS
4. Then run composer dump-autoload
