### ISSUE TITLE
$request->user() always return empty when  using with pusher 

### ISSUE THREAD

**Issue by abakermi** [laravel/sanctum#269]
- Sanctum Version: ^2.9
- Laravel Version: ^8.0
- PHP Version: 7.3
- Database Driver & Version:

### Description:
 
 I'm using Sanctum for SPA authentication with pusher enabled broadcast.
I have added `Broadcast::routes(['middleware' => ['auth:sanctum']])`. to `routes/api.php` ,I got always  `403 AccessDeniedHttpException`  
it seem that  `$request->user()` in ` $this->retrieveUser($request, $channelName) ` always return empty . (`Illuminate\Broadcasting\Broadcasters\PusherBroadcaster` )

```
 public function auth($request)
    {
        $channelName = $this->normalizeChannelName($request->channel_name);

        if (empty($request->channel_name) ||
            ($this->isGuardedChannel($request->channel_name) &&
            ! $this->retrieveUser($request, $channelName))) {
            throw new AccessDeniedHttpException;
        }

        return parent::verifyUserCanAccessChannel(
            $request, $channelName
        );
    }
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
