### ISSUE TITLE
Issue using sanctum middle-ware in api.php

### ISSUE THREAD

**Issue by rumus007** [laravel/sanctum#271]
- Sanctum Version: v2.9.4
- Laravel Version: 8.12
- PHP Version: 8
- Database Driver & Version: pgsql v12.6

### Description:
I used a middleware in the api.php for a route for authentication, when an invalid token or not token is sent instead of returning a 401 status code with unauthorized message. It is returning the welcome.blade.php. Am i doing something wrong or is there a bug in the middleware?

![Screenshot from 2021-04-20 14-14-10](https://user-images.githubusercontent.com/51116139/115364879-925abb80-a1e3-11eb-99db-955c6d2bd04c.png)

### Steps To Reproduce:

1. create a login api to produce a token
2. use the valid token in another api route, if the token is invalid should return 401 but receiving the welcome.blade.php contents

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by michabbb** [comment]
So, just in case someone finds this issue in the hope of getting an answer: 

One reason your API call might get a website as response when missing a token or if the token is invalid:
The type of answer Sanctum presents is based on the kind of response the clients expect.
The client lets the server know this by using the header-key:  `Accept`

and this is the result sanctum presents when not using a token or a wrong token based on the "Accept Header":

| Accept Header | Response |
|--------|--------|
| \*/\* | Login View |
| application/json | {"message":"Unauthenticated."} |
