### ISSUE TITLE
Revocation of API tokens does not appear to prevent their usage in subsequent requests

### ISSUE THREAD

**Issue by jameswilddev** [laravel/sanctum#272]
- Sanctum Version: 2.10.0
- Laravel Version: 8.38.0
- PHP Version: 8.0.3
- Database Driver & Version: MySQL 5.7.32 Homebrew

### Description:

I've observed that revoking an API token seems to remove it from the database, but it continues to be accepted on secured routes for unknown reason.  I would assume this is some kind of cache which needs to be flushed, but can't see anything in the [docs regarding revocation](https://laravel.com/docs/8.x/sanctum#revoking-tokens) about such a thing.

Bare minimum repro at: https://github.com/jameswilddev/sanctum-repro - just run `vendor/bin/phpunit` and you'll see it revoke all tokens, but then allow access to a secured route regardless.

### Steps To Reproduce:

- Use Sanctum to generate an API token (`$user->createToken('test')->plainTextToken`).
- Use Sanctum to revoke the API token on a subsequent request (`auth()->user()->currentAccessToken()->delete();`).
- Try to use the API token again on a route requiring auth.
- The request is authenticated despite it using a revoked token.

I have checked that the tokens are definitely being deleted from the database, and that the route being tested rejects requests which are unauthenticated or provide an invalid token:

```
....F                                                               5 / 5 (100%)NULL
string(23) "Tokens BEFORE logout: 2"
string(21) "Tokens AFTER logout: "


Time: 00:00.462, Memory: 26.00 MB

There was 1 failure:

1) Tests\Feature\ExampleTest::test_route_does_not_allow_access_when_logged_out
Response status code [200] is not an unauthorized status code.
Failed asserting that 200 is identical to 401.

/Users/jameswilddev/Documents/Valet/sanctum-repro/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:169
/Users/jameswilddev/Documents/Valet/sanctum-repro/tests/Feature/ExampleTest.php:79
```

Failing test is at the bottom of [this file](https://github.com/jameswilddev/sanctum-repro/blob/master/tests/Feature/ExampleTest.php).  Calls routes defined in [this file](https://github.com/jameswilddev/sanctum-repro/blob/master/routes/api.php).

I've tried `->fresh()` on the user immediately after revoking their tokens.  No effect.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by jameswilddev** [comment]
Done https://laravel.io/forum/revoking-sanctum-api-token-doesnt-appear-to-prevent-use

**Comment by jameswilddev** [comment]
@driesvints I don't seem to be having any luck getting any help on this so far.  Is it worth re-opening here?

**Comment by driesvints** [comment]
@jameswilddev you're performing multiple HTTP calls in a single test method. This isn't supported. Please try separating the HTTP calls. Think of a single test method as a single HTTP call. Prepare the state of the app before executing the call.

**Comment by jameswilddev** [comment]
Aha, thanks, I'll mention this ticket (https://github.com/laravel/framework/issues/27060) so there's a clear link.  This was news to everyone I've shown so far.  Will see if we can make sure we don't have tests doing this going forward.
