### ISSUE TITLE
XSRF-TOKEN and session key change with each request

### ISSUE THREAD

**Issue by chrischerrett** [laravel/sanctum#273]
- Sanctum Version: 2.10
- Laravel Version: 8.12
- PHP Version: 7.2
- Database Driver & Version: MySQL 8

### Description:

Having implemented Authentication for my SPA using Sanctum successfully, I'm finding the http response to every request returns a new value for both the XSRF-TOKEN and the session key. This doesn't seem right. Am I correct to expect this value to remain the same with every response?

As a result, each request therefore sends a new value, and the session never seems to expire as a consequence. Can't work out what's going wrong?

Everything else is working as expected, as per the docs. Any clues?

### Steps To Reproduce:

Kernel:

` 'api' => [\Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class, 'throttle:180,1', \Illuminate\Routing\Middleware\SubstituteBindings::class],`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
