### ISSUE TITLE
Laravel Sanctum just won't authenticate on production...

### ISSUE THREAD

**Issue by HassanAlthaf** [laravel/sanctum#278]
- Sanctum Version: 2.9.2
- Laravel Version: 8.34.0
- PHP Version: 7.4.3
- Database Driver & Version:  MySQL  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

### Description:
I have two apps: A client on Next.js and a backend API with Laravel + Sanctum.

So basically, everything works fine on localhost.

However, I have issues making it work on production. I don't understand what I have done wrong, and I have been doing the same for a long time. For some reason, doesn't work anymore. Keep getting an "Unauthenticated" response everytime I request a resource after logging in.

EDIT: SOLVED.

Goto your Kernel.php, under API, set these middlewares:

```
        'api' => [
			\App\Http\Middleware\EncryptCookies::class,
			\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
			\Illuminate\Session\Middleware\StartSession::class,
			\Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
```

**Comment by HassanAlthaf** [comment]
You will have some issues, you'll have to edit the LoginResponse to not redirect to home as it will think that you're using the "web" guard. I didn't find any other solution so I was forced to do this.

**Comment by RahulDey12** [comment]
did you update the session domain & the stateful domain?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by HassanAlthaf** [comment]
@driesvints I'll have to disagree, this seems like a bug. The solution should be there by default on the documentation.

**Comment by alitnk** [comment]
What I had to do for this was putting my authentication routes in `web` middleware. 
So far so good, no issue yet.

**Comment by klipitkas** [comment]
This seems like a bug that can be replicated.

**Comment by ifui** [comment]
But how do you fix mutiple domain problem? Because one.domain.test will use d second.domain.test.

**Comment by RahulDey12** [comment]
> But how do you fix mutiple domain problem? Because one.domain.test will use d second.domain.test.

You can use comma separated domains. Or just use *. domain.com as wildcard subdomain.

**Comment by c0defre4k** [comment]
Just in case someone got here from google, like me. Those Middlewares should automatically be added by `\Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful`.

The reason why it may not, is probably a configuration issue. Check the `stateful` property in your `config/sanctum.php` or set `SANCTUM_STATEFUL_DOMAINS` env to include your hostname.

**Comment by atta1234** [comment]
> * Sanctum Version: 2.9.2
> * Laravel Version: 8.34.0
> * PHP Version: 7.4.3
> * Database Driver & Version:  MySQL  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
> 
> ### Description:
> I have two apps: A client on Next.js and a backend API with Laravel + Sanctum.
> 
> So basically, everything works fine on localhost.
> 
> However, I have issues making it work on production. I don't understand what I have done wrong, and I have been doing the same for a long time. For some reason, doesn't work anymore. Keep getting an "Unauthenticated" response everytime I request a resource after logging in.
> 
> EDIT: SOLVED.
> 
> Goto your Kernel.php, under API, set these middlewares:
> 
> ```
>         'api' => [
> 			\App\Http\Middleware\EncryptCookies::class,
> 			\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
> 			\Illuminate\Session\Middleware\StartSession::class,
> 			\Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
>             'throttle:api',
>             \Illuminate\Routing\Middleware\SubstituteBindings::class,
>         ],
> ```

Man You are Ammazing,,,,, i was almost ready to deploye the project on cpanel,,, from azure nginx,,,then i found this and wored like a charm,,,,,why laravel not metioned this??  and the default configartion was working on shared hsoting,,,,,but not on nginx,,,,,,and your solution work on nginx,,,  thanks man you savee me,,,

**Comment by fasanyakolawole** [comment]
vb

**Comment by wiren301** [comment]
I'm so happy to find your post. After hours of going into laravel's config for cors/sanctum finally I found that I was short on some middleware's on api group.

**Comment by monirsaikat** [comment]
any update on this ?

**Comment by HassanAlthaf** [comment]
@atta1234 @wiren301 I'm glad this helped you guys. Very weird issue if you use the API routes for Auth instead of Web.

@sea403 Solution is on the first post.
