### ISSUE TITLE
Sanctum conflict Laravel lazyLoading method

### ISSUE THREAD

**Issue by thaisAmanda13** [laravel/sanctum#280]
- Sanctum Version: 2.11
- Laravel Version: 8.43
- PHP Version: 7.4
- Database Driver & Version: 
- Postgres Version: 13

### Description:
Sanctum has a conflict when trying to use lazyLoading method and throw an exception ([Laravel\\Sanctum\\PersonalAccessToken] but lazy loading is disabled)

```"message": "Attempted to lazy load [tokenable] on model [Laravel\\Sanctum\\PersonalAccessToken] but lazy loading is disabled.",
  "exception": "Illuminate\\Database\\LazyLoadingViolationException",
  "file": "/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php" 
```

### Steps To Reproduce:
Open up the AppServiceProvider class and add the following to the boot() method:

``` 
Model::preventLazyLoading(! app()->isProduction( ));
```

**Comment by driesvints** [comment]
I can't reproduce this. Please provide the exact code to reproduce this.

**Comment by danilopinotti** [comment]
Fixed with https://github.com/laravel/framework/pull/37503
