### ISSUE TITLE
Wrong user data

### ISSUE THREAD

**Issue by robertnicjoo** [laravel/sanctum#284]
- Sanctum Version: ^2.11
- Laravel Version: ^8.12
- PHP Version: 7.4
- Database Driver & Version: MySql

### Description:

When I login by API and create token for user returning data are correct, but when I use that token to get user in other controllers it returns wrong user.

### Steps To Reproduce:

Here is screenshots of postman requests

Login with user `postman@test.com`

![001](https://user-images.githubusercontent.com/8672823/121457747-5e756880-c9d2-11eb-8cd8-df09a4cf95aa.png)

Receive user info of user `admin@admin.com`

![002](https://user-images.githubusercontent.com/8672823/121457783-70570b80-c9d2-11eb-989d-9c35a0e37edd.png)

```php
  public function index(Request $request)
  {
    $user = $request->user();
    return response()->json($user); // returning image # 2 above
  }
```

**Comment by robertnicjoo** [comment]
The problem was that I am using `uuid` for my users table and `personal_access_tokens` table is morphable with `id` so I changed it to `uuidMorphs` and now it's working

```php
Schema::create('personal_access_tokens', function (Blueprint $table) {
  $table->bigIncrements('id');
  $table->uuidMorphs('tokenable');
  $table->string('name');
  $table->string('token', 64)->unique();
  $table->text('abilities')->nullable();
  $table->timestamp('last_used_at')->nullable();
  $table->timestamps();
});
```

**Comment by volpacchiotto** [comment]
I got such problem. Authenticator returned wrong users. Users have GUID as ID. The issue was add 
`protected $keyType = 'string';`
into User class. That indicates to laravel not to transform string GUID to integer ID.
