### ISSUE TITLE
TOKENABLE_ID always check for Integer value even if KeyType is set to String in Model

### ISSUE THREAD

**Issue by almostkareem** [laravel/sanctum#288]
- Sanctum Version: CURRENT
- Laravel Version: 8.X
- PHP Version: 8.X
- Database Driver & Version: MYSQL

### Description:

`SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'PS1xiTzPhE491' for column 'tokenable_id' at row 1 (SQL: insert into `personal_access_tokens` (`name`, `token`, `abilities`, `tokenable_id`, `tokenable_type`, `updated_at`, `created_at`)`

### Steps To Reproduce:

`class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $primaryKey = 'userId';

    public $incrementing = false;

    protected $keyType = 'string';
..
}
`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by almostkareem** [comment]
Hello, thanks for your feedback.

However I think Sanctum's TOKENABLE_ID should go along with its parent model's primary key type to prevent this from happening. 

Thanks
