### ISSUE TITLE
/sanctum/csrf-cookie Should use api instead of web middleware

### ISSUE THREAD

**Issue by Hill-98** [laravel/sanctum#289]
- Sanctum Version: 2.11.2
- Laravel Version: 8.47.0
- PHP Version: 8.0.7
- Database Driver & Version: Mariadb 10.5.10

### Description:
`/sanctum/csrf-cookie` Should use api instead of web middleware

The middleware currently used for routing is the `web` group, but the  [documentation](https://laravel.com/docs/8.x/sanctum#sanctum-middleware) is to add the `EnsureFrontendRequestsAreStateful` middleware to the `api` group. but it won't work unless it is added to the `web` group or the global middleware.

**Comment by driesvints** [comment]
The current behavior is the intended one.
