### ISSUE TITLE
cookies are not set if you send "/sanctum/csrf-cookie"  request from different domain

### ISSUE THREAD

**Issue by osamaAbdullah** [laravel/sanctum#297]
- Sanctum Version: 2.11.2
- Laravel Version: 8.55.0
- PHP Version: 7.4.20
- Database Driver & Version:

### Description:

Laravel is running on: http://127.0.0.1:8000/
front end (vue) is running on: http://localhost:3000/ 

I put all following in my .env file
```
COOKIE_SAME_SITE_POLICY=strict
SESSION_SECURE_COOKIE=false
SESSION_DOMAIN='.127.0.0.1'
SANCTUM_STATEFUL_DOMAINS='.localhost,.localhost:3000,127.0.0.1,127.0.0.1:8000,::1'
```
When I'm trying to authenticate from a different domain it gives 419 error CSRF token mismatch, the first request "http://127.0.0.1:8000/sanctum/csrf-cookie" which must set the cookies does not set anything however if I try the same request inside laravel instance it sets the cookies and works as expected

how every the same request sets the cookies successfully in postman

### Steps To Reproduce:

1. install laravel "composer create-project laravel/laravel sanctum"
2. change "'supports_credentials' => false," to "'supports_credentials' => true," from /config/cors.php
3. set up the vue app on "http://localhost:3000/" and send a request to "http://127.0.0.1:8000/sanctum/csrf-cookie" and it will not set the cookies.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
