### ISSUE TITLE
currentAccessToken()->delete throw exception on test but works fine in real

### ISSUE THREAD

**Issue by maxzod** [laravel/sanctum#298]
- Sanctum Version: `^2.11.2`
- Laravel Version: `8.54`
- PHP Version: `7.3|^8.0`
- Database Driver & Version:

### Description:
deleting current user token works fine
but in test it throw exception

### Steps To Reproduce:
`routes/api.php`
```php

Route::prefix('auth')->middleware('auth:sanctum')->group(function () {
    Route::delete('/sign_out', [AuthController::class, 'signOut']);
   /// other routes
});
```
``app\Http\Controllers\Api\Auth\AuthController.php``
```php
//  * delete the current access token
    public function signOut(Request $request)
    {
        $request->user()->currentAccessToken()->delete();
        return  response()->json(
            [
                'message' => 'auth.signed_out_successfully'
            ],
        );
    }
```

the test 
```php
  public function test_when_signed_out_the_token_gets_deleted()
    {

        // * create new user
        User::factory()->create(['email' => 'max@zod.com']);

        // * sign in the user
        $response = $this->withHeaders(
            ['accept' => 'Application/json']
        )->postJson('/api/auth/sign_in', [
            'email' => 'max@zod.com',
            'password' => 'top_secret',
            'device_name' => 'test_device'
        ]);
        $response->assertStatus(200);
        $object = $response->getData();
        $array = json_decode(json_encode($object), true);
        $token = $array['data']['token'];


        /// get current tokens count from the server
        $queryResult  = DB::select('select Count(*) from personal_access_tokens')[0];
        $array = json_decode(json_encode($queryResult), true);
        $tokensCount = $array["Count(*)"];
        $this->assertEquals("1", $tokensCount);


        // * sign out request
        $response = $this->withHeaders(
            [
                'accept' => 'Application/json',
                'Authorization' => 'Bearer ' . $token,
            ]
        )->delete('/api/auth/sign_out');
        dd($response->getData());
        $response->assertStatus(200);


        /// get current tokens count from the server
        $queryResult  = DB::select('select Count(*) from personal_access_tokens')[0];
        $array = json_decode(json_encode($queryResult), true);
        $tokensCount = $array["Count(*)"];
        $this->assertEquals("0", $tokensCount);
    }

```
stack trace 
```
{
  "message": "Call to undefined method Laravel\Sanctum\TransientToken::delete()",
  "exception": "Error",
  "file": "<path>\app\Http\Controllers\Api\Auth\AuthController.php",
}
```

**Comment by Noor600** [comment]
try this 
$user->tokens()->where('id', auth()->id())->delete();

**Comment by maxzod** [comment]
> try this
> $user->tokens()->where('id', auth()->id())->delete();

i think this will not work even if it worked it will delete the entire tokens for this user and i need only to delete the current device token

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by maxzod** [comment]
https://stackoverflow.com/questions/68911775/currentaccesstoken-delete-throw-exception-on-test-but-works-fine-in-real

**Comment by muradhajiyev** [comment]
@maxzod I'm wondering if you solved this issue. I'm also trying to access `currentAccessToken` from test which returns null. But it works in application.

**Comment by maxzod** [comment]
@muradhajiyev 
nope still the same
