### ISSUE TITLE
Laravel Sanctum authentication failure on live server even after successful authentication

### ISSUE THREAD

**Issue by 3gHub** [laravel/sanctum#299]
- Sanctum Version: 2.11
- Laravel Version: 8.5
- PHP Version: 7.4
- Database Driver & Version:

### Description:

Completed the application setup with a complete authentication feature using sanctum and it is working fine on the local machine. 
But when I uploaded the application on the live server, the authentication returns the token too. But when the routes under sanctum middleware are accessed, it just returns an unauthenticated error.

I also changed the `.env` files as:

`SANCTUM_STATEFUL_DOMAINS=`
`SESSION_DOMAIN=`

But still it is not working. Kindly help on this issue.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
