### ISSUE TITLE
Expired session cookies pilling up, causing 431 HTTP Errors

### ISSUE THREAD

**Issue by Neodark7** [laravel/sanctum#300]
- Sanctum Version: 2.11.2
- Laravel Version: 8.49.2
- PHP Version: 7.4.19
- Database Driver & Version: MySQL 8
- Nuxt Version: 2.15.7
- Nuxt Auth Version: 5.0.0-1616003482.75c20e6

### Description:

I'm having this weird issue (only happening in Firefox as of my testing) where a new "dead" cookie is added everytime i login.

First login, no issue, i have only two HttpOnly cookies.

![image](https://user-images.githubusercontent.com/7981869/132367767-9ee3c59a-4e10-4505-91eb-007e0ecd5fd4.png)

After 5 login/logout attemps, i have now 8 HttpOnly cookies, and it keeps pilling up until i eventually get an 431 HTTP error code from nginx

![image](https://user-images.githubusercontent.com/7981869/132368960-530869b5-fbf0-4323-a0c4-fbd9b220a790.png)

I'm using the laravel app as an api only, with a separate nuxt app using the nuxt auth plugin configured for laravel sanctum. Everything works fine with Chrome, the cookies are not pilling up like on Firefox.

### Steps To Reproduce:

I don't have steps to reproduce this behavior, that's the first project i'm seeing this. Tell me if there is any other information i can give to resolve this issue.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
