### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by stackerito** [laravel/sanctum#301]
- Sanctum Version: 2.11
- Laravel Version: 8.55.0
- PHP Version: 8.0.10
- Database Driver & Version: MySQL 8.0.26

### Description:
I am using 4 Docker container for each service: PHP-FPM for Laravel API, Node for Next.js frontend, MySQL and NGINX
Frontend is served from localhost:3000 and the Laravel API is served from localhost:8080

I have a registration form on `localhost:3000/register` and I send request to `localhost:8080/api/register`.
The user is actually created on the database, but I am getting the following error:

>Access to XMLHttpRequest at 'http://localhost:8080/api/register' from origin 'http://localhost:3000' has been blocked by >CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Why do I get this error and how can the user be created if there is an error?

`cors.php` seem to be configured properly to send the `Access-Control-Allow-Origin` header:
```
    'paths' => ['api/*', 'sanctum/csrf-cookie'],

    'allowed_methods' => ['*'],

    'allowed_origins' => ['http://localhost:3000'],

    'allowed_origins_patterns' => ['*'],

    'allowed_headers' => ['*'],

    'exposed_headers' => [],

    'max_age' => 0,

    'supports_credentials' => true
```

Sanctum does not seem to return an `Access-Control-Allow-Origin`  although it's defined in `cors.php`

### Steps To Reproduce:

Create separate Docker containers for each service: php, node, mysql, nginx.
Then try to send the post request from the frontend to the backend on two different ports.

This is how I send the post request to my backend API:
```
            axios.post(
                'http://localhost:8080/api/register',
                {
                    email: email,
                    password: password
                },
                {
                    withCredentials: true,
                    headers: {
                        'Content-Type': 'application/json',
                        Accept: 'application/json',
                    },
                }
            )
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
