### ISSUE TITLE
Call to a member function prepare() on null

### ISSUE THREAD

**Issue by Sahandi81** [laravel/sanctum#317]
- Sanctum Version: ^2.12 
- Laravel Version: 8.69.0
- PHP Version: 7.4
- Database Driver & Version: mongoDB

### Description:

After the system was fully set up, everything was working properly. But after the changes for create new token by `$user->createToken('token_base_name')->plainTextToken` keep give me `Call to a member function prepare() on null`.

`personal_access_tokens` table exists but its empty.

```
Schema::create('personal_access_tokens', function (Blueprint $table) {
            $table->morphs('tokenable');
            $table->string('name'); # OR $table->string('token_base_name'); ->> no changes
            $table->string('token', 64)->unique();
            $table->text('abilities')->nullable();
            $table->timestamp('last_used_at')->nullable();
            $table->timestamps();
        });
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Sahandi81** [comment]
@driesvints  
i fixed it, but I had to change Non-project files.

in `vendor/laravel/sanctum/src/PersonalAccessToken.php` for mongoDB must be use `use Jenssegers\Mongodb\Eloquent\Model`
Think about it and leave a update.
GL Guys
