### ISSUE TITLE
An incorrectly formed bearer token causes SQL error

### ISSUE THREAD

**Issue by mgsmus** [laravel/sanctum#318]
- Sanctum Version: 2.12.1
- Laravel Version: 8.70.2
- PHP Version: 8.0.9
- Database Driver & Version: PostgreSQL 13.2

### Description:
An incorrectly formed token (a token with a quote or double quote on the left) causes SQL error on the server. We discovered it as a result of a mistake made by our frontend engineer.

The line causing the error:
https://github.com/laravel/sanctum/blob/2.x/src/PersonalAccessToken.php#L64

>Invalid text representation: 7 ERROR:  invalid input syntax for type bigint: ""138" (SQL: select * from "personal_access_tokens" where "personal_access_tokens"."id" = "138 limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bigint: \"\"138\" (SQL: select * from \"personal_access_tokens\" where \"personal_access_tokens\".\"id\" = \"138 limit 1) at /var/www/project/releases/20211110162512/vendor/laravel/framework/src/Illuminate/Database/Connection.php:703)

An example of an incorrectly formed token: (Note the double quotes on the left.)
`"138|E5bndnZUVCQUVkYWphbUV2SmlGcHg1UWFZeG0yRGd`

**I don't know if this is a bug or something that I should be dealing with.** We fixed the part that caused the token to be corrupted on our part, but I wanted to let you know because the 500 error gives me the feeling that something is wrong.

### Steps To Reproduce:

```
curl --request POST \
  --url https://project.test/api/broadcasting/auth \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer "138|E5bndnZUVCQUVkYWphbUV2SmlGcHg1UWFZeG0yRGd' \
  --header 'Content-Type: application/json'
```

**Comment by driesvints** [comment]
The token should indeed be properly formatted but it's true that we shouldn't just throw a query exception. Appreciating PR's for this.

**Comment by driesvints** [comment]
Closing this as the related pr was closed.
