### ISSUE TITLE
Object of type Illuminate\\Auth\\AuthManager is not callable

### ISSUE THREAD

**Issue by websanova** [laravel/sanctum#319]
- Sanctum Version: 2.12.1
- Laravel Version: 8.70.2
- PHP Version: 8.0.5
- Database Driver & Version: Not a db issue

### Description:

Issue getting Sanctum to work, it seems to be having an issue with the "auth:sanctom" guard. Really not sure what's going on.

I'm able to perform a login and get a valid token such as  "1|qyjIc9HqH4pCKP3jltEaFDtUpM9knHLqWofRDAj2".

But then any request to the route, with or without token just keeps giving this error. It does seem like it's running through all the middleware fine up until it hits this. I can also confirm the `SanctumServiceProvider` is running. 

**NOTE:** I was originally on php 7.4 before trying 8 and it was throwing the same error but with a different message: "Function name must be a string".

---

class: "Error"
code: "SystemError"
file: "/home/vagrant/starter/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 168
msg: "Object of type Illuminate\\Auth\\AuthManager is not callable"
status: "error"
trace: 
0: "#0 /home/vagrant/starter/laravel/vendor/fruitcake/laravel-cors/src/HandleCors.php(52)"
1: "Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#1 /home/vagrant/starter/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167)"
2: "Fruitcake\\Cors\\HandleCors->handle()\n#2 /home/vagrant/starter/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103)"
3: "Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#3 /home/vagrant/starter/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697)"
4: "Illuminate\\Pipeline\\Pipeline->then()\n#4 /home/vagrant/starter/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672)"
5: "Illuminate\\Routing\\Router->runRouteWithinStack()\n#5 /home/vagrant/starter/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636)"
6: "Illuminate\\Routing\\Router->runRoute()\n#6 /home/vagrant/starter/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625)"
7: "Illuminate\\Routing\\Router->dispatchToRoute()\n#7 /home/vagrant/starter/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167)"
8: "Illuminate\\Routing\\Router->dispatch()\n#8 /home/vagrant/starter/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128)"
9: "Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()\n#9 /home/vagrant/starter/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103)"
10: "Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()\n#10 /home/vagrant/starter/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142)"
11: "Illuminate\\Pipeline\\Pipeline->then()\n#11 /home/vagrant/starter/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111)"
12: "Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()\n#12 /home/vagrant/starter/laravel/public/index.php(52)"
13: "Illuminate\\Foundation\\Http\\Kernel->handle()\n#13 {main}"

### Steps To Reproduce:

Run any request against a route with "auth:sanctum" guard.

**Comment by daniel-avis** [comment]
This worked for me, using code from Laravel 10

Create a file called `Authenticate.php` in the `Controllers/Middleware` folder

```
<?php

namespace App\Http\Middleware;

use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param mixed $request
     */
    protected function redirectTo($request): ?string
    {
        return $request->expectsJson() ? null : route('login');
    }
}
```

Register the route middleware in the `Http/Kernel.php`

```
protected $routeMiddleware = [
  'auth' => \App\Http\Middleware\Authenticate::class,
  ...
];
```
