### ISSUE TITLE
Wrong guard config breaks the application

### ISSUE THREAD

**Issue by omalizadeh** [laravel/sanctum#323]
- Sanctum Version: 2.12.2
- Laravel Version: 8.73.2
- PHP Version: 8.0.11
- Database Driver & Version: MySql 8.0.21

### Description:
I have a guard in config named 'api' with driver set to 'sanctum' (for users auth). then i added api guard to sanctum configuration file (guard section that added recently, default is array containing web). Then all of requests ended up in empty 500 errors, no logs, nothing. I know i made mistakes by adding api guard to sanctum config But it must not break the application with no details.

### Steps To Reproduce:

1. new guard 'api': sanctum driver and users as providers
2. set default guard to api
3. add api guard to sanctum guard config array
4. make a request to a valid route

**Comment by driesvints** [comment]
If you want to improve the error output, we're open to prs. Thanks
