### ISSUE TITLE
CheckAbilities mistaken sanctum model

### ISSUE THREAD

**Issue by afiqiqmal** [laravel/sanctum#332]
- Sanctum Version: 2.13.0
- Laravel Version: 8.78.1
- PHP Version: 8.1
- Database Driver & Version: Mysql 8

### Description:

I have a problem when to use abilities middleware where i used sanctum for different model (TokenVendor) and user authentication using another model (User). The CheckAbilities middleware detect User model instead of Sanctum model.

### Steps To Reproduce:

Here is the sample of my routes

```
Route::middleware('auth:sanctum')->group(function() {
    ....
    ....
    Route::prefix('auth')->group(function() {
         Route::post('login', [ApiAuthController::class,  'login']);
    });
 
    Route::middleware('auth:admin')->group(function() {
           Route::middleware('ability:news')->group(function() {   <---- it detect as User model not sanctum TokenVendor model
                
           });
    });
})
```

The problem is it detect as User model not sanctum TokenVendor model which cause an error where User model doesn't using HasApiToken trait. But when i change `$request->user()` to `$request->user('sanctum')` in CheckAbilities middleware, its working fine.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
