### ISSUE TITLE
Error stdClass::createToken() when Issuing API Tokens

### ISSUE THREAD

**Issue by iszakur** [laravel/sanctum#345]
- Sanctum Version: 2.14
- Laravel Version: 8.12
- PHP Version: 7.4.6
- Database Driver & Version:

### Description:
I tried to issue api token with query builder in function's model. with this code :
```
$user = $this->auth_model->get_user($this->data['username']);
$token = $user->createToken('my-app-token')->plainTextToken;
```
, but showing a error `Call to undefined method stdClass::createToken()`. 
It sould be `App\Models\Auth::createToken()`. How to change `stdClass` become `App\Models\Auth`? so I can issue the api token.

#### This is the way I create token in controller :

```
namespace App\Http\Controllers;
use App\Models\Auth;

class AuthController extends Controller
{
    private $auth_model;

    public function __construct()
    {
        $this->auth_model = new Auth();
    }

    public function login(Request $request)
    {
        $this->data = [
            'username'  => $request->username,
            'password'  => $request->password,
        ];

        // get data user username dan password
        $user = $this->auth_model->get_user($this->data['username']);
        $token = $user->createToken('my-app-token')->plainTextToken;  //error comes from this code
    }

}
```

#### This is code of the Auth model :
```
namespace App\Models;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;
use Laravel\Sanctum\HasApiTokens;

class Auth extends Model
{
    use HasApiTokens;

    protected $table = 'tb_user';

    public function get_user($username)
    {
        return DB::table($this->table)
                ->select('username', 'name', 'password')
                ->where([['username', '=', $username], ['rec_stat', '=', 'A'], ['is_user_login', '=', 'Y']])
                ->limit(1)
                ->first();
    }
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
