### ISSUE TITLE
expiration configuration is not working

### ISSUE THREAD

**Issue by enkhtulga-gantsagaan** [laravel/sanctum#347]
- Sanctum Version: ^2.14
- Laravel Version: 8.*
- PHP Version: ^7.3|^8.0
- Database Driver & Version:

### Description:
When i try to change default null value to 2 minutes for testing. Expiration is not working. There is no effect for frontend. no 419 error. still get 200 status.
<img width="182" alt="Screen Shot 2022-03-15 at 13 53 30" src="https://user-images.githubusercontent.com/100667943/158315645-774fcd5d-2348-4946-9e30-85f16bc36a32.png">

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by alex-unruh** [comment]
I have the same problem: 
If the the expiration is set to 30 minutes, for example, i had Unauthenticated when a try to use the token in any requests. But if expiration is set to 500000 for example, it works. Is this expiration time really set in minutes in sanctum config file as described in docs? I'm using laravel 9.

**Comment by alex-unruh** [comment]
I have the same problem. Apparently carbon's gt (greater than) method has a problem when calculating dates from SQL Server. For some reason laravel stores dates in my SQL Server database with Y-d-m format and MySQL with Y-m-d format. So there is a confusion in the isValidAccessToken method of Sanctum's Guard class. Laravel 9.

**Comment by alex-unruh** [comment]
I have the same problem. Apparently carbon's gt (greater than) method has a problem when calculating dates from SQL Server. For some reason laravel stores dates in my SQL Server database with Y-d-m format and MySQL with Y-m-d format. So there is a confusion in the isValidAccessToken method of Sanctum's Guard class to calculate the expiration defined in config/sactum.php.
