### ISSUE TITLE
SPA auth not working in Safari

### ISSUE THREAD

**Issue by JonathanDoelan** [laravel/sanctum#359]
Given: An api runs at `api.example.com` and an app runs on `app.example.com`, where the api is used for spa authentication.

SPA-auth does not work in Safari. There are some same-site cookie issues there.

**Comment by driesvints** [comment]
No issue template was filled out here. Please try a support channel first:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
