### ISSUE TITLE
Suggestion to add symmetric cipher.

### ISSUE THREAD

**Issue by hsndmr** [laravel/sanctum#364]
Suggest:
When a generated token is encrypted with a symmetrical algorithm like AES, it will more secure.

How to Brute Force Attack?
A sanctum token consists of two sections. One of them sanctum token id. Another is a random string. We know a site that uses Laravel Sanctum.  We will register it, then we will get a sanctum token.  Our token will be `2|IZwA2V92sNBBBIRsp0K5VuxhiSN1ec4PcenDrs5Y`. We are sure the next token will be `3|(random-string)` and previous token will be `1|(random-string)`. Then we will try to generate random token using `Str::random(40)` method. We will try to find correct token. Our token will hash at each attempt, then it will search the database. If we use a symmetric algorithm, we need to decipher the token before attempting it.

**Comment by driesvints** [comment]
The ID was originally added because of performance reasons: https://github.com/laravel/sanctum/pull/136. I don't think we'll change this anytime soon, sorry.
