### ISSUE TITLE
Sanctum Package stopped working after upgrading to laravel 9

### ISSUE THREAD

**Issue by hksofttronix** [laravel/sanctum#368]
- Sanctum Version: 2.15.1
- Laravel Version: 9.0
- PHP Version: 8.1
- Database Driver & Version: MSSQL 2018

### Description:
I have recently upgraded my project to Laravel and after that package is showing below response.
{
    "message": "Unauthenticated."
}

### Steps To Reproduce:
Upgrade project from Laravel 8 to 9.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
