### ISSUE TITLE
$request->user() is blank in the controller instance

### ISSUE THREAD

**Issue by StanleyMasinde** [laravel/sanctum#373]
- Sanctum Version: 2.15.1
- Laravel Version: 9.13.0
- PHP Version: 8.1.7
- Database Driver & Version: MySQL 8.0.29

### Description:
I am using Sanctum for API authentication. The *auth:sanctum* middleware is working correctly the problem is when I try to use 
`$request->user()` to get the current user in the controller. `$request->user()` is always null in when live but Finds the correct user when testing. I've had to do as shown in the screenshot below for it to work in production.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/35426405/175818127-1efc2da7-0b09-4408-ac87-defc0af89bfd.png">

Below is a screenshot of the test
<img width="502" alt="image" src="https://user-images.githubusercontent.com/35426405/175818248-2d912f3c-77f8-42fe-980d-ffe8ce80cdc1.png">
The above test finds the correct user in `$request->user()` but is blank when running the application. I'm wondering if it is because the Guard I'm using is not the default guard?

### Steps To Reproduce:

1. Start a new project with Sanctum2. 
2. Create a secondary Authentication guard and use it with Sanctum (The non SPA mode)
3. Try and access the user from a controller instance or even the route callback function.

**Comment by StanleyMasinde** [comment]
Thank you @driesvints. I understand you have a very tight schedule and therefore sorry for this. I reported this here because I believe it is a bug. That is not the intended behaviour from my description above, you can see I already have a work around.

I've had a look at how the sanctum user is retrieved by sanctum and it seems to only use the 'web' guard?
https://github.com/laravel/sanctum/blob/863b610662bc09091fb73188f127d65eb64d3398/src/Guard.php#L56

I suspect that might be the cause. Also the reason my tests are passing might be because the sanctum mock adds a user directly to the the guard to sanctum and not the Guard being tested and sets the default guard to sanctum. So $request->user() will return the user for default guard in tests which is sanctum like in the line below
https://github.com/laravel/sanctum/blob/863b610662bc09091fb73188f127d65eb64d3398/src/Sanctum.php#L75

Seems like Sanctum only works with the web Guard?

**Comment by driesvints** [comment]
Yes.

**Comment by StanleyMasinde** [comment]
Thank you for the clarification
