### ISSUE TITLE
Date format on personal access token

### ISSUE THREAD

**Issue by DossantosED** [laravel/sanctum#374]
- Sanctum Version: 2.14.1
- Laravel Version: 9.17.0
- PHP Version: 8.1.6
- Database Driver & Version: SQL Server 2016

### Description:
I have a problem when I want to authenticate myself with Laravel Sanctum, when I generate a login the record of the creation and update dates in the personal_access_tokens table saves them with #Y:d:m format, apparently this means that when you want to send the token, the system it takes it as expired, returning the message "Unauthenticated", this only happens with SQL Server, in MySql the dates are saved correctly with the #Y:m:d format, how can I solve it?

### Steps To Reproduce:
$user->createToken('auth_token')->plainTextToken;

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
