### ISSUE TITLE
Bug while feature testing: hitting the same endpoint twice on the same test, with different bearer token yields the same user.

### ISSUE THREAD

**Issue by yob-yob** [laravel/sanctum#377]
- Sanctum Version: v2.15.1
- Laravel Version: v9.20.0
- PHP Version: v8.1.8
- Database Driver & Version: sqlite / :memory: 

### Description:

Bug while testing and using `$this->getJson()` and authenticating using `Bearer` token, twice on a single test function.

`$this->getJson()` will return a correct `$request->user()` data on first run, 
while on second it returns the same data from the first run on the second run.

### Steps To Reproduce:

[Bug Report Repository](https://github.com/yob-yob/laravel-sanctum-bug-report)

you can run `php artisan test --filter=SanctumTokenTest`

Test file is found on: `tests/Feature/SanctumTokenTest.php`

**Comment by driesvints** [comment]
You can't perform two HTTP requests in the same test method. That's not supported.
