### ISSUE TITLE
[Feature request] v3 wish list

### ISSUE THREAD

**Issue by ankurk91** [laravel/sanctum#381]
Hi @driesvints 

I noticed that v3 is around the corner now.
I am trying bring the most requested features here.

## 1. Prevent updating `last_used_at` on each request

The `last_used_at` column is getting updated on every request.

**Related PR/issues**
* https://github.com/laravel/sanctum/issues/293
* https://github.com/laravel/sanctum/issues/207
* https://github.com/laravel/sanctum/issues/141
* https://github.com/laravel/sanctum/issues/91
* https://github.com/laravel/sanctum/pull/253

**Possible solutions**
* Use `app()->terminating()` callback
* OR Use a lottery to update the column
* OR A config option to configure the time interval, for example every 15 minutes

## 2. Expiry per token
I think it is already in the plan.

**Related PR**
* https://github.com/laravel/sanctum/pull/252

## 3. Use native model pruning
We can use native `model:prune` command now and can make the package slim by removing the [PruneCommand](https://github.com/laravel/sanctum/blob/3.x/src/Console/Commands/PruneExpired.php) Command

**Related PR**
* https://github.com/laravel/sanctum/pull/348
* https://github.com/laravel/sanctum/pull/241

## 4. Remove deprecated Middleware

* CheckScopes
* CheckForAnyScope

## 5. Introduce `tokenHasAbility()` method on Model

Allows to check specific ability, it its different from `$token->can`, can() returns true when it is `*` in abilities

```php
public function tokenHasAbility(string $ability): bool
{
      return $this->accessToken && array_key_exists($ability, array_flip($this->accessToken->abilities));
}
```

**Comment by driesvints** [comment]
Thanks @ankurk91. That's helpful! I'll remember this issue when I'm creating tomorrow's changelog.

**Comment by ankurk91** [comment]
The `last_used_at` is most requested one, please consider this in version 3.x

**Comment by driesvints** [comment]
v3 has already been released. If you want to propose that than feel free to send it to master for v4 👍

**Comment by MostafaRabia** [comment]
What about `last_used_at` now?

**Comment by fbramato** [comment]
this has been implemented even on v4?

**Comment by piotrczech** [comment]
bump

**Comment by KhairulAzmi21** [comment]
last_used_at caused a deadlock . can we have this fix soon ?
