### ISSUE TITLE
Prune command doesn't take expires_at into account

### ISSUE THREAD

**Issue by bjhijmans** [laravel/sanctum#384]
- Sanctum Version: 3.0.0
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:

### Description:
As mentioned here https://github.com/laravel/sanctum/pull/252#issuecomment-1198125142 the `sanctum:prune-expired` does not prune models based on their expires_at column, but only on the global `sanctum.expiration` config setting. This is counterintuitive and incorrect. The prune command should be updated for v3.

**Comment by driesvints** [comment]
Can you send in a PR?

**Comment by bjhijmans** [comment]
I don't have the time right now. I can look do it next week if nobody beats me to it. I just got notified about the comment because I made the expires_at PR and turned it into an issue.

**Comment by driesvints** [comment]
A PR was sent in for this.
