### ISSUE TITLE
Can't create new token

### ISSUE THREAD

**Issue by prabodhana** [laravel/sanctum#388]
- Sanctum Version: ^3.0
- Laravel Version: ^9.19
- PHP Version: 8.0.21
- Database Driver & Version:

### Description:
Try to create token but getting this error
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'expires_at' in 'field list' (SQL: insert into `personal_access_tokens` (`name`, `token`, `abilities`, `expires_at`, `tokenable_id`, `tokenable_type`, `updated_at`, `created_at`) values (127.0.0.1, f88ca44394bf69ece76ed9e67f5e96a7aeb3b8ea61a713e02c8aafeb0bc7c400, ["*"], ?, 1, App\Models\User, 2022-07-30 04:44:54, 2022-07-30 04:44:54))

**Comment by raksbisht** [comment]
@prabodhana  delete the table personal_access_tokens  and try to run **php artisan migrate** .

**Comment by prabodhana** [comment]
> @prabodhana delete the table personal_access_tokens and try to run **php artisan migrate** .

I removed the personal_access_tokens migration inside laravel migration folder. Laravel default personal_access_tokens migration file doesn't have 'expired_at' filed. But inside sanctum folder migration file have that field.

**Comment by raksbisht** [comment]
> > @prabodhana delete the table personal_access_tokens and try to run **php artisan migrate** .
> 
> I removed the personal_access_tokens migration inside laravel migration folder. Laravel default personal_access_tokens migration file doesn't have 'expired_at' filed. But inside sanctum folder migration file have that field.


This PR (https://github.com/laravel/laravel/commit/6e1103180b439bf6970b4a50e9e42cc5de9f9bf3) to Laravel has fixed your issue, please update your code as per this PR or update your laravel.

**Comment by driesvints** [comment]
Please read the upgrade guide. You need to add a new column to your app. We'll release the skeleton on Tuesday.
