### ISSUE TITLE
API Authentication issues with PAT

### ISSUE THREAD

**Issue by LabSilo** [laravel/sanctum#392]
- Sanctum Version: 2.15.1
- Laravel Version: 9.24.0
- PHP Version: 8.1.3
- Database Driver & Version: MySQL Driver - 10.3.35-MariaDB

### Description:
Okay it is a bit complicated.
I'm using Laravel as a back-end for Vue. the back-end is supposed to be completely compatible and usable by both web-application and mobile application.
Because of that i need both web authentication (which has CSRF token checks and more on) and API authentication which is done via PAT by `Authorization: Bearer` header.
The web authentication is all working without a single issue but i have faced several issues since i tried to use PAT authentication.
My `Authenticate.php` is edited so it checks the authentication and respond if not.
Here it is the `handle` method of `Middleware\Authenticate.php`:
```
public function handle($request, \Closure $next, ...$guards): RedirectResponse|JsonResponse|Response
    {
        if (!Auth::check()) {
            if (!$request->expectsJson() && !Str::startsWith($request->getPathInfo(), '/api/')) {
                throw new UnauthorizedHttpException('web');
            }

            return ApiError(GeneralStatuses::Forbidden->value, null, [], 403);
        }

        return $next($request);
    }
```
My default authentication guard is `web`, all default from laravel.
The middleware above was returning the `Forbidden` response because `Auth::check()` was false whenever i used PAT authentication. However, `Auth::guard('sanctum')->check()` is true.
So i tried to change the default guard of the laravel to `sanctum` but that brought several other issues, including the disability to use `Auth::login($user)` and more.
I ended up reverting the authentication's default guard to `web` but modify the `Authenticate.php` middleware as below:
```
public function handle($request, \Closure $next, ...$guards): RedirectResponse|JsonResponse|Response
    {
        $sanctumAuthorized = Auth::guard('sanctum')->check();
        $defaultGuardAuthorized = Auth::check();
        if ($sanctumAuthorized && !$defaultGuardAuthorized && $request->hasHeader('Authorization')) {
            Auth::login(Auth::guard('sanctum')->user());

            return $next($request);
        }

        if (!$defaultGuardAuthorized) {
            if (!$request->expectsJson() && !Str::startsWith($request->getPathInfo(), '/api/')) {
                throw new UnauthorizedHttpException('web');
            }

            return ApiError(GeneralStatuses::Forbidden->value, null, [], 403);
        }

        return $next($request);
    }
```
I'm somehow sure that it shouldn't be like that and something is wrong that i need to do such checks in the middleware, but i found it working for me anyway.
But there's a bigger concern with that, as you can see there's a `$request->hasHeader('Authorization')` check, without that my logout route always failed silently to logout the user.
The logout route been throwing no exceptions but the correct status code, however i was still able to make requests to `auth:sanctum` protected routes.
Because the `$sanctumAuthorized`  in `Authenticate.php` middleware has been still true after the logout so it was logging in the user that is set in sanctum guard.
After all, i'm not sure about the security of the back-end because of the works that needed to be done.

### Steps To Reproduce:
[The Repository specially made for this issue to reproduce](https://github.com/LabSilo/SanctumBugReport)
During the creation of the repository i found that the latest changes to `Authenticate.php` doesn't fix all the issues
Details and tests are available in `tests/Feature/LoginTest`.

**Comment by driesvints** [comment]
I have no 
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by systemsolutionweb** [comment]
lol
