### ISSUE TITLE
Can't Regenerate X-XSRF-TOKEN Cookies in My Production

### ISSUE THREAD

**Issue by jsvelte** [laravel/sanctum#393]
- Sanctum Version: ^2.14.1
- Laravel Version: 9.0
- PHP Version: ^8.0.2
- Database Driver & Version:  Heroku pgql version 14.4

### Description:
I have two folder:
`backend` for laravel-breeze https://laravel.com/docs/9.x/starter-kits#laravel-breeze
`frontend` for next.js application.

I follow all the instruction given through `breeze-next` and my development seems perfectly find.

I also successfully deployed my laravel-api with the helps of this articles.
And configured necessary database to established a connection
https://dev.to/moose_said/deploy-laravel-projects-with-database-for-free-5778
![image](https://user-images.githubusercontent.com/108642414/185899847-de1decb8-466c-40dd-8c32-35735a8c8e42.png)

I separately deployed my frontend next.js in to vercel and configured the 
NEXT_PUBLIC_BACKEND_URL into my deployed laravel-api in heroku 
![image](https://user-images.githubusercontent.com/108642414/185900176-591470c5-fe57-4037-a90d-48b546b6e08e.png)

### First Problem that I solved
I managed to fix the Cross-Origin Resource Sharing (CORS) in my backend with this implementation in laravel
![image](https://user-images.githubusercontent.com/108642414/185900679-55c8a4d8-ecb1-4bc1-9262-641ac6dfef72.png)

and also add the `FRONTEND_URL` in heroku production and it works
![image](https://user-images.githubusercontent.com/108642414/185900978-4fc02622-dcdd-44d9-8b9e-240a96e133da.png)

### Second Problem 
`CSRF token mismatch`
This is the error also that I somehow fixed but I'm not sure this is the good idea
![image](https://user-images.githubusercontent.com/108642414/185901754-8b66f382-e8d1-4340-b0a1-be4ee6fd26dd.png)

I also changed the session driver into `cookie`
![image](https://user-images.githubusercontent.com/108642414/185902251-eb5d84a9-a1f5-4b3e-aece-41cbf366eb79.png)

## PROBLEM
So, now I can register but cannot generate the cookies for my headers like `X-XSRF-TOKEN`
I also tried to login but cannot regenerate the cookies need to authenticate the user
There is no problem in my development only in my production
![image](https://user-images.githubusercontent.com/108642414/185903901-d5340332-cd30-432e-b523-68418fe73fbf.png)
It says that:
this attemp to set cookie via a set-cookie header was block because it had "samesite=lux" but came from a cross site response which was not a response to a top level navigation

PLEASE HELP ME......
GOD BLESS YOU ALL

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
