### ISSUE TITLE
EnsureFrontendRequestsAreStateful forces cookies to be SameSite=lax

### ISSUE THREAD

**Issue by hackel** [laravel/sanctum#396]
While trying to change the cookie SameSite setting to strict, I discovered that Sanctum's `EnsureFrontendRequestsAreStateful` middleware overrides the value set in `config/session.php` and forces it to "lax".

https://github.com/laravel/sanctum/blob/861f834441aecdcb8050521e7e517062684f0977/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php#L46

This isn't mentioned in the docs anywhere and was difficult to find.  What is the reason for overriding the user-specified value?  I would suggest that either the `session.same_site` config value should be respected, or an additional config value should be added to `sanctum.php` so that users can customize this setting as needed.

**Comment by driesvints** [comment]
I don't know myself but given that we haven't had any reports about this so far I'm sure there's a good reason for.

**Comment by hackel** [comment]
Here is the thread which first pointed me toward Sanctum as the culprit for this behaviour.  Several people are experiencing this issue.

https://laracasts.com/discuss/channels/laravel/setting-same-site-in-seassonphp-doesnt-do-anything
