### ISSUE TITLE
Converting an nvarchar data type to datetime resulted in a value outside the allowable range. 

### ISSUE THREAD

**Issue by ilescu** [laravel/sanctum#401]
- Sanctum Version: 3.0.0
- Laravel Version: 9.19.0
- PHP Version: 8.1.0
- Database Driver & Version:  SqlSrv

### Description:

SQLSTATE [22007]: [Microsoft] [ODBC Driver 17 for SQL Server] [SQL Server] Converting an nvarchar data type to datetime resulted in a value outside the allowable range. (SQL: update [personal_access_tokens] set [last_used_at] = 2022-10-13 09: 00: 05.623 where [id] = 56)

**Comment by RahulDey12** [comment]
@ilescu why there is a decimal value in seconds. Are you casting that or something?
