### ISSUE TITLE
In one case, the token is invalidated

### ISSUE THREAD

**Issue by erxiaosoul** [laravel/sanctum#409]
- Sanctum Version: 3.0.1
- Laravel Version: 9.3.10
- PHP Version: 8.1.12
- Database Driver & Version: mysql 8.0

### Description:
When I did `php artisan make:scope` I added a global scope,The code is as follows:
```
/**
     * Apply the scope to a given Eloquent query builder.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $builder
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @return void
     */
    public function apply(Builder $builder, Model $model)
    {
        $builder->when(request('search'), function ($query) {
            $query->where('name', 'like', '%' . request('search') . '%');
        });
    }
```
When I query the list of users, the pass-in parameter (search) is fine if it is in Chinese, but immediately invalidates the token if it is in English.

### Steps To Reproduce:

I built a temporary repository, [click here](https://github.com/erxiaosoul/laravel-scope) to access the code
https://github.com/erxiaosoul/laravel-scope

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
