### ISSUE TITLE
When creating new token, id is 0 and plainTextToken starts with 0|

### ISSUE THREAD

**Issue by jochemgruter** [laravel/sanctum#413]
- Sanctum Version: 2.15.1
- Laravel Version: 8.83.27
- PHP Version: 8.1.11
- Database Driver & Version: MySQL 8.0.28

### Description:
When I create a token this way, the id of the token is 0 and the token start with 0|
`auth()->user()->createToken('test');`
The id in the database do have a valid number.

When creating the token this way, it works find:

`User::find(auth()->user()->id)->createToken('test');`
or
`auth()->user()->refresh()->createToken('test');`

**Comment by RahulDey12** [comment]
I don't think this could happen because the Id is a Primary Key and I should be greater than 0.

**Comment by driesvints** [comment]
There's no steps to reproduce this.
