### ISSUE TITLE
Specifying different model for sanctum middleware

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/sanctum#419]
Hi, I'm currently working on a Laravel 9 project where I'm using personal access tokens for more than just my `User` model. I'm using it for my `Microservice` model. I've created a token for a microservice in my application and have an entry in my personal access tokens table with the tokenable type as `App\Models\Microservice` so this part is working.

I've gone ahead and extended my Laravel's `auth.php` config file to include a `microservice` guard as I presume this is required.

```php
'guards' => [
    'api' => [
        'driver' => 'session',
        'provider' => 'users',
    ],
    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],
    'microservice' => [
        'driver' => 'session',
        'provider' => 'microservices',
    ],
],

'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => App\Models\User::class,
    ],
    'microservices' => [
        'driver' => 'eloquent',
        'model' => App\Models\Microservice::class,
    ],

    // 'users' => [
    //     'driver' => 'database',
    //     'table' => 'users',
    // ],
],
```

Then, inside of my controller's constructor method, right now I'm using `auth:sanctum`, but I'd like to be able to use sanctum and pass a different model type to it as when I use `auth:microservice` this then bypasses sanctum entirely.

Would be great if this could be a feature or help suggesting what I could do to modify and get this working.

**Comment by btxtiger** [comment]
>Then, inside of my controller's constructor method, right now I'm using auth:sanctum, but I'd like to be able to use sanctum >and pass a different model type to it as when I use auth:microservice this then bypasses sanctum entirely.
Can you explain this in other words?
If you like to bypass sanctum auth, you just don't need to call it?

**Comment by driesvints** [comment]
I think this already works. It just involves protecting your route with `auth:sanctum`. The PAT model is morphable so it will just return whatever model is attached to it. 

Then you can just request the model with `$request->user()`:

```php
public function controllerMethod(Request $request)
{
     $microservice = $request->user(); // will be instance of App\Models\Microservice
}
```

You don't need to add a new guard or provider I think.

**Comment by sts-ryan-holton** [comment]
I see now, thank you :)
