### ISSUE TITLE
419 CSRF token mismatch on first page load

### ISSUE THREAD

**Issue by sylica** [laravel/sanctum#422]
Hi!

I got a site with Nuxt 2 FE and Laravel BE. It's working fine but I came across a strange bug.

For example if you open [this](https://hangszer.schnellbach.hu/product/epiphone-korina-explorer-2001--167) page it gets 419 CSRF token mismatch error, you reload the page and after that everything works fine.

I've red a ton of fixes for this error but none of them worked unfortunately (sanctum config, cors config, .env SANCTUM_STATEFUL_DOMAINS etc.)

I hope somebody had the same problem and has a solution for it, thanks!

P.S. my stack:
- Sanctum Version: 2.15.1
- Laravel Version: 8.83.27
- PHP Version: 7.4.7

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
