### ISSUE TITLE
new session is created on every request.

### ISSUE THREAD

**Issue by quyle92** [laravel/sanctum#425]
- Sanctum Version: 2.15.1
- Laravel Version: 9.52.0
- PHP Version: 8.1.16
- Database Driver & Version: MYSQL v.8.0.28

### Description:
- installing sanctum with default config and `\Illuminate\Session\Middleware\StartSession` is enabled in both `app/Http/Kernel.php` and `config/sanctum.php` so on every request, it goes through `StartSession` twice, which makes new session created on every request.
- Removing that middleware in either file solves problem.
### Steps To Reproduce:
- install breeze + sanctum with default config.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by quyle92** [comment]
thanks for your reply.
I already upgraded to latest version.
The problem is at `handle()` of `EnsureFrontendRequestsAreStateful` where `StartSession` is included. So if I use `web` middleware group to all of my routes, then it means `StartSession` will run twice during request lifecycle.

**Comment by quyle92** [comment]
any update on this?
