### ISSUE TITLE
PersonalAccessToken unauthenticated in read connection

### ISSUE THREAD

**Issue by ivankrister** [laravel/sanctum#428]
- Sanctum Version: 3.2.1
- Laravel Version: 9.52.0
- PHP Version: 8.1
- Database Driver & Version: MySql8

### Description:

Unauthenticated after login when using the read connections

### Steps To Reproduce:

1. Create database cluster with write and read cluster in my case i use digitalocean database cluster
2. Step up the database config similar on docs

```
'mysql' => [
    'read' => [
        'host' => [
            '192.168.1.1',
            '196.168.1.2',
        ],
    ],
    'write' => [
        'host' => [
            '196.168.1.3',
        ],
    ],
    'sticky' => true,
    'driver' => 'mysql',
    'database' => 'database',
    'username' => 'root',
    'password' => '',
    'charset' => 'utf8mb4',
    'collation' => 'utf8mb4_unicode_ci',
    'prefix' => '',
],
```

3. Create token similar on docs

`$user->createToken($request->device_name)->plainTextToken;`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
