### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by salahdidi** [laravel/sanctum#432]
- Sanctum Version: ^3.2
- Laravel Version: 10.4.1
- PHP Version: 8.1.10
- Database Driver & Version: mysql 8.0.29 

### Description:
 i keep getting Array to string conversion when try generate token  with 
   if (auth()->guard('api')->attempt($cerdentials)) {
  $token = Auth::user()->createToken("web_token"); 
  }
  i did same code for laravel 9 and php 8 and it work well
![Screenshot from 2023-03-26 14-23-43](https://user-images.githubusercontent.com/104596961/227778614-565446ac-008c-43cb-ad8c-d4cd6440ea5c.png)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
