### ISSUE TITLE
Config option to disable TokenAuthenticated events

### ISSUE THREAD

**Issue by binaryfire** [laravel/sanctum#436]
It'd be great if we could disable `event(new TokenAuthenticated($accessToken));` via a config option. The default events don't make sense in a multi-db multi tenancy setup because the ids aren't scoped to tenant. I'm sure there are other situations where it'd be useful too.

**Comment by driesvints** [comment]
I'm not sure this is needed? Just don't listen/react to this event if you don't need it?

**Comment by binaryfire** [comment]
Functionally that’s true but it makes Telescope’s events section much harder to read. Every API request adds an event to the list that needs to be ignored. It’s added some confusion amongst my junior devs too.
