### ISSUE TITLE
Sanctum 3.2.2 is broken EnsureFrontendRequestsAreStateful error

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/sanctum#438]
### Sanctum Version

3.2.2

### Laravel Version

10.9.0

### PHP Version

8.1.13

### Database Driver & Version

MySQL

### Description

I've just upgraded Laravel Sanctum from 3.2.1 -> 3.2.2 and instantly, without any code changes in my project get a fatal exception thrown in the `EnsureFrontendRequestsAreStateful.php` file.

Downgrading back to 3.2.1 resolves the problem.

### Steps To Reproduce

Here's the error found:

- File: `/var/www/api/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php`
- Line: 32
- Message: _Object of class Closure could not be converted to string_

**Comment by Scaenicus** [comment]
I was three minute slower: #439

**Comment by driesvints** [comment]
Reverted in v3.2.3, thanks all.
