### ISSUE TITLE
I am using Swoole to start a web service and using Sanctum for authentication

### ISSUE THREAD

**Issue by lwhdev** [laravel/sanctum#445]
### Sanctum Version

2.15.1

### Laravel Version

7

### PHP Version

7.4

### Description

I am using Swoole to start a web service and using Sanctum for authentication. However, there is an issue: after successfully logging out, the token table in the database is cleared but still shows as logged in status. Only after restarting Swoole and making a new request will it prompt for a token again. How can I clean up excess authentication data to avoid continuously occupying memory and keeping users in a logged-in state?

### Steps To Reproduce

```
Auth::user()->tokens()->delete();
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
