### ISSUE TITLE
Issue with currentAccessToken() method return type

### ISSUE THREAD

**Issue by albertoelias123** [laravel/sanctum#447]
### Sanctum Version

3.2.5

### Laravel Version

10.13.5

### PHP Version

8.2.7

### Description

I have been analyzing the `currentAccessToken()` method in the codebase and noticed an inconsistency with the declared return type. Currently, the method is declared to return `\Laravel\Sanctum\Contracts\HasAbilities`, which seems incorrect.

After debugging this function at runtime using `dd($user->currentAccessToken())`, I discovered that it can actually return an instance of `Laravel\Sanctum\PersonalAccessToken` or `null`.

To ensure code clarity and accurate type hinting, I kindly request updating the return type declaration of the `currentAccessToken()` method to `\Laravel\Sanctum\PersonalAccessToken`. This adjustment will reflect the actual behavior of the method and provide developers with the correct information regarding the return value.

![personal_access](https://github.com/laravel/sanctum/assets/41304037/4f0d3bfd-99b9-4b4f-b662-4235a4c7ab84)

### Steps To Reproduce

// Null
$user = Auth::user();
dd($user->currentAccessToken());

and

// Laravel\Sanctum\PersonalAccessToken
$user = Auth::user();
$user->createToken('app');
dd($user->currentAccessToken());

**Comment by driesvints** [comment]
Thank you but we don't consider wrong docblock types to be bugs. It seems you sent in a PR so let's see how that goes. Thanks.

**Comment by albertoelias123** [comment]
No problem! How can I contribute in cases where there are discrepancies in docblock types or similar code improvements? Thanks!
