### ISSUE TITLE
expires_at dont set a default value from config.sanctum.expiration

### ISSUE THREAD

**Issue by nerpianicolindo** [laravel/sanctum#453]
### Sanctum Version

3.2.5

### Laravel Version

9.52.9

### PHP Version

8.1.8

### Database Driver & Version

10.4.25-MariaDB

### Description

In my project, i set a value to variable "config.sanctum.expiration", but i don't know why when i'm creating the sanctum's token, the variable dont set the default value of expires_at column in BBDD. is this the real work?? we need to set the date manually??

### Steps To Reproduce

//Is needed to use code like this
```
$fechaHoraActual = new DateTime();
$fechaHoraActual->add(new DateInterval('PT' . config('sanctum.expiration') . 'M'));
$token = auth()->user()->createToken('LaravelSanctumAuth', array('*'), $fechaHoraActual);
```

//instead of just this
`$token = auth()->user()->createToken('LaravelSanctumAuth')`

**Comment by driesvints** [comment]
This isn't set on the token but on the guard.
