### ISSUE TITLE
Token Expiration issue

### ISSUE THREAD

**Issue by sandipiweb** [laravel/sanctum#469]
### Sanctum Version

^3.0

### Laravel Version

9.19

### PHP Version

8.0.2

### Database Driver & Version

mysql

### Description

Mobile App Api

after create token, token has been expired after some time li 48 even  i set   'expiration' => null, in config/sanctum.php.

how  i can set token lifetime ?

### Steps To Reproduce

step 1 
Auth::attempt()   check user credential, if match then  step 2  is run

step 2

createToken('MyApp')->plainTextToken;  run this method for creating token

stape 3

send to the user

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
