### ISSUE TITLE
Expiration config not working

### ISSUE THREAD

**Issue by michele-grifa** [laravel/sanctum#470]
### Sanctum Version

3.3.0

### Laravel Version

9.52.15

### PHP Version

8.0."

### Description

I'm trying to set the expiration at 240 minutes, but when I create the token, it is instantly invalid. In the database the expires_at column is null on all the tokens generated.

### Steps To Reproduce

- Set expiration to 240 in `config/sanctum.php`
- Create a new token
- Try to use the token in a request
- Response is Unauthenticated, the token is not valida anymore

**Comment by driesvints** [comment]
Could it be that this is due to https://github.com/laravel/sanctum/pull/459#discussion_r1312952194 ?

If you apply the change from https://github.com/laravel/sanctum/commit/95a0181900019e2d79acbd3e2ee7d57e3d0a086b in the sanctum.php config file does it work for you?

**Comment by michele-grifa** [comment]
No, the problem is present in a fresh install of Sanctum.

**Comment by michele-grifa** [comment]
I found the solution. I'm using SQL Server 2019 and with that I need to specify `->timestamps(2)` in the migration file or the date are always wrong.
