### ISSUE TITLE
Data truncated for column 'tokenable_id'

### ISSUE THREAD

**Issue by guilherme90** [laravel/sanctum#472]
### Sanctum Version

3.3

### Laravel Version

10.10

### PHP Version

8.1

### Database Driver & Version

MySQL

### Description

i'm using Uuid as primary key in my models, and by default, the sanctrum use bigint on column "tokenable_id". This is a bug?

### Steps To Reproduce

- Use `HasUuids` in models

![Screenshot 2023-09-26 194820](https://github.com/laravel/sanctum/assets/2879939/bbed23d7-2c66-4d19-a71c-380411ae74b4)

![Screenshot 2023-09-26 194845](https://github.com/laravel/sanctum/assets/2879939/92f65637-528b-4c8e-8499-098b9b66381c)

![Screenshot 2023-09-26 194740](https://github.com/laravel/sanctum/assets/2879939/79fec5ef-e701-4625-b7ab-88916edcb701)

**Comment by crynobone** [comment]
See https://laravel.com/docs/10.x/sanctum#migration-customization

**Comment by guilherme90** [comment]
Hey @crynobone,
I'm run the command, but this not work!

![Screenshot_5](https://github.com/laravel/sanctum/assets/2879939/5d341096-5331-486c-b274-b0d784878d66)
![Screenshot_6](https://github.com/laravel/sanctum/assets/2879939/0cfed9c0-5fdb-4957-bdf3-540b8a7e3f05)
![Screenshot_7](https://github.com/laravel/sanctum/assets/2879939/9ad370fc-c4cd-4f5a-b24d-b4b1d90d0a97)

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by guilherme90** [comment]
Got it, but just to be clear that this appears to be a library bug. When I run the command to publish the migrations to my project, it seems to create a migration incompletely.

**Comment by guilherme90** [comment]
Solved!

Replace 
```php
$table->morphs('tokenable');
```

to
```php
$table->uuidMorphs('tokenable');
```
