### ISSUE TITLE
Direct links to API routes

### ISSUE THREAD

**Issue by user191365** [laravel/sanctum#489]
Attempting to access the API routes directly (from the address bar) does not work and results in an unauthenticated request. This happens because the referer and origin headers are not present on the first page load. Is it an expected behavior? The default web middleware stack would correctly authenticate such requests.

Use cases: routes that serve files: bookmarking that link will not work on subsequent visits; confirmation links.

Would be nice to have a built-in workaround and the limitation outlined in the docs.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
