### ISSUE TITLE
Standalone tokens (without user model / tokenable_type relationship)

### ISSUE THREAD

**Issue by TheNewSound** [laravel/sanctum#494]
Hi, 

Currently the polymorphic relationship 'tokenable' of a PersonalAccessToken is not Nullable. This forces tying a token to a model.

I'm looking to create two types of tokens: 
1. The usual authentication tokens (also handle authorization via abilities).
2. Tokens solely for authorization. These can be given to unauthenticated requests (e.g. no specific user logged in) that need a bit more access than just 'guests'.

For this last purpose it would be nice if Sanctum supports creating (and using the authorization checks of) tokens that aren't tied to an application model.

**Comment by driesvints** [comment]
I'm sorry but right now this is out of scope of this package and we don't have immediate plans to add this.
