### ISSUE TITLE
Issue with overriding default model

### ISSUE THREAD

**Issue by Alyka** [laravel/sanctum#504]
### Sanctum Version

4.x

### Laravel Version

10.x

### PHP Version

8.x

### Description

Overriding the default model throws an error

`Laravel\\Sanctum\\NewAccessToken::__construct(): Argument #1 ($accessToken) must be of type Laravel\\Sanctum\\PersonalAccessToken, Core\\Models\\SanctumModel given, called in /var/www/html/vendor/laravel/sanctum/src/HasApiTokens.php on line 52`

### Steps To Reproduce

- Install laravel,
- Override sanctum model in your service providers `Sanctum::usePersonalAccessTokenModel(SanctumModel::class);`
- `use` the `Laravel\Sanctum\HasApiTokens` trait in your User model
- Call `$user->createToken('token_name')`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
