### ISSUE TITLE
Could we have a more descriptive method on the request to access the model?

### ISSUE THREAD

**Issue by KrimoPixelsmith** [laravel/sanctum#505]
When using the HasApiTokens trait on a model other than User, the corresponding model has to be accessed through `$request->user()`. Wouldn't a more generic `$request->model()` be more appropriate/readable?

**Comment by RahulDey12** [comment]
this is the way laravel authenticated user can be taken. if you want more logical way you can use `Auth::user()`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
