### ISSUE TITLE
Only in Sanctum 3 - Fix/unable to logout

### ISSUE THREAD

**Issue by WillRy** [laravel/sanctum#512]
### Sanctum Version

3.*

### Laravel Version

10.*

### PHP Version

8.2

### Database Driver & Version

Any

### Description

Hello everybody,

They recently fixed a bug in sanctum, which made consecutive logout and login impossible with different users. The fix works very well, but it was only applied to Sanctum 4.

The bug still remains in sanctum 3, which is used by laravel 10, which is a version that still has time for bug updates.

Could you bring this solution to laravel 10? this would help a lot

The fix that worked was applied in issue #511

Thanks to everyone

### Steps To Reproduce

The same of this issue:

https://github.com/laravel/sanctum/pull/511

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. ~~Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.~~

Thanks!
