### ISSUE TITLE
Sanctum should not change session config

### ISSUE THREAD

**Issue by aliakbarazizi** [laravel/sanctum#516]
### Sanctum Version

1.6.1

### Laravel Version

10.4.1

### PHP Version

8.2

### Description

sanctum changing app session config without telling developer and this is not something a library should do.

https://github.com/laravel/sanctum/blob/4.x/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php#L34

I can see for authentication you want to force `lax`, but why you changing config? I had code which was working base on these config and sactum simply just overwrite it. why a library should even change a project config? that was a real surprised for me

relative issues:
https://laracasts.com/discuss/channels/laravel/setting-same-site-in-seassonphp-doesnt-do-anything

### Steps To Reproduce

just try to install laravel sanctum and use session config file after sanctum fully loaded

**Comment by aliakbarazizi** [comment]
I think its better to leave the config unchanged, either by removing this line and use `Lax` directly instead of reading from session config or provide a option in sanctum config to disable this behavior

**Comment by driesvints** [comment]
Sorry but right now we don't have any plans to change this as this could impact existing apps. If you want, you're free to attempt a PR so we can look at the code involved.

**Comment by aliakbarazizi** [comment]
> Sorry but right now we don't have any plans to change this as this could impact existing apps. If you want, you're free to attempt a PR so we can look at the code involved.

I didn't understood why this is exists in first place, should a library mutate project config? I never see something like this before,

If there is no plan isn't better to include it in document, because this is really a big issue. I think it should be in huge warning in document which tell this middleware will mutate your project config file, be aware!
