### ISSUE TITLE
Vendor publish creates new migration for personal_access_tokens even with already existing table

### ISSUE THREAD

**Issue by Sushma-Mercantile** [laravel/sanctum#527]
### Sanctum Version

4.0.2

### Laravel Version

11

### PHP Version

8.2.12

### Description

In a Laravel project that uses Sanctum, when I run php artisan vendor:publish, it keeps creating fresh migration files for the personal access token table. This results in multiple migration files for the same table that leads to conflict while running migration.

![image](https://github.com/user-attachments/assets/9193f5c3-aaa9-4db2-a509-1ac1407daca8)

Also, I found the previous methods to ignoreMigrations is also removed and used publishesMigrations instead. ignoreMigrations would have prevented repeated creation of migration.

### Steps To Reproduce

1. Require laravel/sanctum
2. Run php artisan vendor:publish multiple times
3. This also runs sanctum-migrations and it copies migration to project\database\migrations
4. Even when there is migration copied already, it stills copies the migration resulting in multiple migration for same table.

**Comment by wfern** [comment]
It's because of the migration configuration in the database config file: `database.migrations.update_date_on_publish`

```php
    'migrations' => [
        'table' => 'migrations',
        'update_date_on_publish' => true,
    ],
```
Maybe it should be false by default.

**Comment by Sushma-Mercantile** [comment]
Thank you. This solved the issue for me, it was true by default!
