### ISSUE TITLE
auth:sanctum middleware on logout not set user_id field null session

### ISSUE THREAD

**Issue by anas-js** [laravel/sanctum#533]
### Sanctum Version

^3.3

### Laravel Version

^10.10

### PHP Version

^8.1

### Database Driver & Version

mysql-8.0.30-winx64

### Description

When I log out with `auth:sanctum` middleware , the `user_id` field on sessions tabel is not set to null, unlike when I don't use it.

```php
Route::post('/logout', function (Request $request) {
    Auth::guard('web')->logout();
    $request->session()->invalidate();
    $request->session()->regenerateToken();
    return ['done' => 'ok'];
})->middleware('auth:sanctum');
```

user id same :
[![enter image description here][1]][1]

The problem is that I have routers that use this middleware and sometimes I need to log out for some reason. When using `auth:sanctum`, the `user_id` is not set to null.

i don't use tokens , i use sessions and cookies with sanctum,
and sessions driver is database

  [1]: https://i.sstatic.net/19cvt9N3.png

### Steps To Reproduce

1 - logout route set middleware auth:sanctum
2 - send request to this endpoint

**Comment by driesvints** [comment]
You need to completely flush the session: https://github.com/laravel/sanctum/pull/511/files#diff-5e6d713ef085c38496fc32e7303af79e38e8aaabbb076fab41fe93f214070cb1R64

**Comment by anas-js** [comment]
> You need to completely flush the session: https://github.com/laravel/sanctum/pull/511/files#diff-5e6d713ef085c38496fc32e7303af79e38e8aaabbb076fab41fe93f214070cb1R64

I saw the link, but how can I do that?
