### ISSUE TITLE
Deprecated warning from  Laravel\Sanctum\HasApiTokens::createToken()

### ISSUE THREAD

**Issue by shokanshi** [laravel/sanctum#548]
### Sanctum Version

4.0,.4

### Laravel Version

11.33.2

### PHP Version

8.4.1

### Description

I am getting this warning running the Laravel app on PHP 8.4.1.

> LOG.warning: Laravel\Sanctum\HasApiTokens::createToken(): Implicitly marking parameter $expiresAt as nullable is deprecated, the explicit nullable type must be used instead in ...\vendor\laravel\sanctum\src\HasApiTokens.php on line 49

### Steps To Reproduce

Just running the laravel 11.33.2 app on PHP 8.4.1 will get the warning message.

**Comment by crynobone** [comment]
Fixed via https://github.com/laravel/sanctum/pull/542 and pending a release
