### ISSUE TITLE
Adding signature to the token value

### ISSUE THREAD

**Issue by enygma** [laravel/sanctum#9]
When the tokens are created, they're generated as hashed of a random string (based on the code in `Str::random` it's from `random_bytes` which is good). However, this also leaves them open to possible brute force attempts as a persistent attacker could start guessing hash values in the `sha256` space trying to locate a valid token value.

I'd suggest that a "secret" value be added for the token such that it can be used in an HMAC hashing process for the token to help prove that the token came from the application it was signed by. This wouldn't 100% prevent the brute forcing of the token but it would reduce the risk of an attacker just guessing the hash value.

Here's the proposal:

**For generation:**
1. Generate the hash as it's currently done (a `sha256` hash, always 256 bits long)
2. Use the secret value to generate the HMAC signature of the hash (`sha512` would be a good choice here`)
3. Concatenate the two hashes

**For validation:**
1. Split the token at the 256 bits location to give the hash and the signature
2. Validate the signature to ensure the token is from the same application.

Concatenating the values like this also has the benefit of increasing the entropy of the token returned to the requesting frontend as it's length is dramatically increased.

**Comment by taylorotwell** [comment]
Is it computationally feasible to brute force a token with such entropy?

**Comment by enygma** [comment]
The higher the number of users there are the higher the chance an attacker would find a valid SHA256 value (without the signature) that was valid, assuming there's no timeout as suggested in the other issue I posted (#5).

SHA256 is better than something simpler like SHA1, but it's still possible to brute force a SHA256 token relatively quickly as there's a pretty small character space to check (a-Z, 0-9).

This particular suggestion won't do as much to reduce the risk level as the timeout will, but implementing both controls will only reduce the risk level more. I think at the very least providing the option to users could be a good thing.

**Comment by fragkp** [comment]
Suggestion by an none security guy (me): Wouldnt it be enough to just set the config `session.encrypt` to `true`?

**Comment by MikeGlennFWC** [comment]
I've been looking over this type of authentication over the last few days, an implementation I like is the AWS Signature Version 4 implementation.


The key benefit in my mind is that the secret/token never gets transmitted as both ends only generate a signature to compare.

there

**Comment by rennokki** [comment]
Wouldn't be an Encrypt function good to be applied on the final hash token? Or is it computationally heavy?

https://laravel.com/docs/6.x/encryption

**Comment by halaei** [comment]
Seeing the unique index/constraint on token column in personal_access_tokens database made me worried of time-based attacks. However, I see the tokens are hashed, which definitely makes time-based attacks harder, but I am not sure if someday somebody can invent a method to breaks that as well.
Time-based attacks aside, directly indexing and searching for string tokens is not necessary:
```php
$token = $request->bearerToken();
$accessToken = $model::where('token', hash('sha256', $token))->first();
``` 
My suggestion is to put id as well as string token in the bearer token, separating them by a dot character, which is file for Authorization header. So the bearer tokens will be of form `/[^\.]+\..+/`, e.g `123.somerandomstringofsize80`. Now the code to query for tokens will be something like:
```php
$token = $request->bearerToken();
if (! preg_match('/([^\\.]+)\\..+/', $token, $parts)) {
    return;
}
$accessToken = $model::where('id', $parts[1])->first();
if (! $accessToken || ! hash_equals($accessToken->token, hash('sha256', $parts[2]))) {
    return;
}
```

Again I am not sure the current implementation is practically unsafe, but my guess is that my suggestion is safer, and not too complicated.

**Comment by halaei** [comment]
Also I want to note that my suggestion is not that new. It is exactly how validating remember tokens in laravel or validating access/refresh tokens in passport are currently implemented. I see not but the same strategy other places as well.

**Comment by rennokki** [comment]
Hm, i think we should take the Passport's example on encrypting tokens using the public/private set of keys that are generated on the machine.

**Comment by nanaaikinson24** [comment]
Can Sanctum be used with multiple guards?

**Comment by AhmedSharaf98** [comment]
You can increase the token length that would possibly make brute force even harder.

**Comment by enygma** [comment]
One note on the suggestion about increasing the token length - the signature suggestion here isn't meant to help prevent brute forcing. It's designed to help ensure the integrity of the token. Yes, they could in theory brute still brute force the entire token, but this suggestion provides an extra level on top of that and could remove a requirement to fetch data from the database (an expensive operation).

**Comment by driesvints** [comment]
See https://github.com/laravel/sanctum/pull/124
